# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.wan_request_body import WanRequestBody

class TestWanRequestBody(unittest.TestCase):
    """WanRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WanRequestBody:
        """Test WanRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WanRequestBody`
        """
        model = WanRequestBody()
        if include_optional:
            return WanRequestBody(
                duration = '',
                job_type = '',
                prompt = '',
                reference_asset_id = '',
                reference_asset_ids = [
                    ''
                    ],
                reference_video_asset_id = '',
                resolution = ''
            )
        else:
            return WanRequestBody(
                duration = '',
                job_type = '',
                prompt = '',
                reference_asset_id = '',
                reference_video_asset_id = '',
                resolution = '',
        )
        """

    def testWanRequestBody(self):
        """Test WanRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
