# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_integration_accounts_response import SuccessIntegrationAccountsResponse

class TestSuccessIntegrationAccountsResponse(unittest.TestCase):
    """SuccessIntegrationAccountsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessIntegrationAccountsResponse:
        """Test SuccessIntegrationAccountsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessIntegrationAccountsResponse`
        """
        model = SuccessIntegrationAccountsResponse()
        if include_optional:
            return SuccessIntegrationAccountsResponse(
                data = inoue_ai_sdk.models.integration_accounts_response.IntegrationAccountsResponse(
                    items = [
                        inoue_ai_sdk.models.integration_account.IntegrationAccount(
                            access_level = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            display_name = '', 
                            handle = '', 
                            icon_url = '', 
                            id = '', 
                            kind = '', 
                            label = '', 
                            last4 = '', 
                            model_count = 56, 
                            owner_org_id = '', 
                            owner_user_id = '', 
                            platform = '', 
                            status = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    total = 56, ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessIntegrationAccountsResponse(
                data = inoue_ai_sdk.models.integration_accounts_response.IntegrationAccountsResponse(
                    items = [
                        inoue_ai_sdk.models.integration_account.IntegrationAccount(
                            access_level = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            display_name = '', 
                            handle = '', 
                            icon_url = '', 
                            id = '', 
                            kind = '', 
                            label = '', 
                            last4 = '', 
                            model_count = 56, 
                            owner_org_id = '', 
                            owner_user_id = '', 
                            platform = '', 
                            status = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    total = 56, ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessIntegrationAccountsResponse(self):
        """Test SuccessIntegrationAccountsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
