# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_page_invite import SuccessPageInvite

class TestSuccessPageInvite(unittest.TestCase):
    """SuccessPageInvite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessPageInvite:
        """Test SuccessPageInvite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessPageInvite`
        """
        model = SuccessPageInvite()
        if include_optional:
            return SuccessPageInvite(
                data = inoue_ai_sdk.models.page_invite.PageInvite(
                    items = [
                        inoue_ai_sdk.models.invite.Invite(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            invited_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            member_id = '', 
                            model_id = '', 
                            pool_id = '', 
                            responded_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            status = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            weight_percent = 56, )
                        ], ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessPageInvite(
                data = inoue_ai_sdk.models.page_invite.PageInvite(
                    items = [
                        inoue_ai_sdk.models.invite.Invite(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            invited_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            member_id = '', 
                            model_id = '', 
                            pool_id = '', 
                            responded_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            status = '', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            weight_percent = 56, )
                        ], ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessPageInvite(self):
        """Test SuccessPageInvite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
