# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.prompt_run import PromptRun

class TestPromptRun(unittest.TestCase):
    """PromptRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptRun:
        """Test PromptRun
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptRun`
        """
        model = PromptRun()
        if include_optional:
            return PromptRun(
                avatar_profile_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user_id = '',
                engine_params_json = None,
                engine_type = '',
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                model_id = '',
                prompt_version_id = '',
                resolved_prompt_text = '',
                run_input_json = None,
                status = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PromptRun(
                avatar_profile_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user_id = '',
                engine_type = '',
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                model_id = '',
                prompt_version_id = '',
                resolved_prompt_text = '',
                status = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPromptRun(self):
        """Test PromptRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
