# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_built_in_list_read_payload import SuccessBuiltInListReadPayload

class TestSuccessBuiltInListReadPayload(unittest.TestCase):
    """SuccessBuiltInListReadPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessBuiltInListReadPayload:
        """Test SuccessBuiltInListReadPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessBuiltInListReadPayload`
        """
        model = SuccessBuiltInListReadPayload()
        if include_optional:
            return SuccessBuiltInListReadPayload(
                data = inoue_ai_sdk.models.built_in_list_read_payload.BuiltInListReadPayload(
                    items = [
                        inoue_ai_sdk.models.caption_template_response.CaptionTemplateResponse(
                            config_style = null, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            highlight_style = null, 
                            id = '', 
                            is_builtin = True, 
                            is_premium = True, 
                            name = '', 
                            slug = '', 
                            sort_order = 56, 
                            subs = null, 
                            tags = [
                                ''
                                ], 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    total = 56, ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessBuiltInListReadPayload(
                data = inoue_ai_sdk.models.built_in_list_read_payload.BuiltInListReadPayload(
                    items = [
                        inoue_ai_sdk.models.caption_template_response.CaptionTemplateResponse(
                            config_style = null, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            highlight_style = null, 
                            id = '', 
                            is_builtin = True, 
                            is_premium = True, 
                            name = '', 
                            slug = '', 
                            sort_order = 56, 
                            subs = null, 
                            tags = [
                                ''
                                ], 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    total = 56, ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessBuiltInListReadPayload(self):
        """Test SuccessBuiltInListReadPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
