# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.model_stats import ModelStats

class TestModelStats(unittest.TestCase):
    """ModelStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelStats:
        """Test ModelStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelStats`
        """
        model = ModelStats()
        if include_optional:
            return ModelStats(
                asset_count = 56,
                identity_asset_count = 56,
                job_count = 56,
                prompt_run_count = 56,
                shared_count = 56
            )
        else:
            return ModelStats(
                asset_count = 56,
                identity_asset_count = 56,
                job_count = 56,
                prompt_run_count = 56,
                shared_count = 56,
        )
        """

    def testModelStats(self):
        """Test ModelStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
