# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.page_recurring_rule_response import PageRecurringRuleResponse

class TestPageRecurringRuleResponse(unittest.TestCase):
    """PageRecurringRuleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageRecurringRuleResponse:
        """Test PageRecurringRuleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageRecurringRuleResponse`
        """
        model = PageRecurringRuleResponse()
        if include_optional:
            return PageRecurringRuleResponse(
                items = [
                    inoue_ai_sdk.models.recurring_rule_response.RecurringRuleResponse(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        event_type = '', 
                        id = '', 
                        is_active = True, 
                        label = '', 
                        last_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        next_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        owner_org_id = '', 
                        owner_type = '', 
                        owner_user_id = '', 
                        recurrence = null, 
                        template = null, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PageRecurringRuleResponse(
                items = [
                    inoue_ai_sdk.models.recurring_rule_response.RecurringRuleResponse(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        event_type = '', 
                        id = '', 
                        is_active = True, 
                        label = '', 
                        last_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        next_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        owner_org_id = '', 
                        owner_type = '', 
                        owner_user_id = '', 
                        recurrence = null, 
                        template = null, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPageRecurringRuleResponse(self):
        """Test PageRecurringRuleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
