# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.api.huggingface_api import HuggingfaceApi


class TestHuggingfaceApi(unittest.TestCase):
    """HuggingfaceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HuggingfaceApi()

    def tearDown(self) -> None:
        pass

    def test_create_huggingface_key(self) -> None:
        """Test case for create_huggingface_key

        Create a Hugging Face API key
        """
        pass

    def test_delete_huggingface_key(self) -> None:
        """Test case for delete_huggingface_key

        Soft-delete a Hugging Face API key
        """
        pass

    def test_list_huggingface_key_shares(self) -> None:
        """Test case for list_huggingface_key_shares

        List the access grants for a Hugging Face key (offset paginated; owner only)
        """
        pass

    def test_list_huggingface_keys(self) -> None:
        """Test case for list_huggingface_keys

        List the caller's accessible Hugging Face keys (offset paginated)
        """
        pass

    def test_probe_huggingface_repo(self) -> None:
        """Test case for probe_huggingface_repo

        Probe a Hugging Face repo (optionally with a caller-accessible key)
        """
        pass

    def test_revoke_huggingface_key_share(self) -> None:
        """Test case for revoke_huggingface_key_share

        Revoke a Hugging Face API key share
        """
        pass

    def test_share_huggingface_key(self) -> None:
        """Test case for share_huggingface_key

        Share a Hugging Face API key with a user or org
        """
        pass

    def test_update_huggingface_key(self) -> None:
        """Test case for update_huggingface_key

        Rename a Hugging Face API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
