# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.prompt_template_response import PromptTemplateResponse

class TestPromptTemplateResponse(unittest.TestCase):
    """PromptTemplateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptTemplateResponse:
        """Test PromptTemplateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptTemplateResponse`
        """
        model = PromptTemplateResponse()
        if include_optional:
            return PromptTemplateResponse(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                example_outputs = [
                    inoue_ai_sdk.models.example_output.ExampleOutput(
                        asset_id = '', 
                        asset_type = '', 
                        asset_url = '', 
                        content_type = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                id = '',
                is_locked = True,
                latest_run_outputs = [
                    inoue_ai_sdk.models.example_output.ExampleOutput(
                        asset_id = '', 
                        asset_type = '', 
                        asset_url = '', 
                        content_type = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                latest_version_json = inoue_ai_sdk.models.prompt_version_response.PromptVersionResponse(
                    content_json = null, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    id = '', 
                    prompt_template_id = '', 
                    version_number = 56, ),
                linked_model_ids = [
                    ''
                    ],
                owner_email = '',
                owner_org_id = '',
                owner_user_id = '',
                tags = [
                    ''
                    ],
                title = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PromptTemplateResponse(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                example_outputs = [
                    inoue_ai_sdk.models.example_output.ExampleOutput(
                        asset_id = '', 
                        asset_type = '', 
                        asset_url = '', 
                        content_type = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                id = '',
                is_locked = True,
                latest_run_outputs = [
                    inoue_ai_sdk.models.example_output.ExampleOutput(
                        asset_id = '', 
                        asset_type = '', 
                        asset_url = '', 
                        content_type = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                owner_email = '',
                owner_org_id = '',
                owner_user_id = '',
                tags = [
                    ''
                    ],
                title = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPromptTemplateResponse(self):
        """Test PromptTemplateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
