# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.asset_response import AssetResponse

class TestAssetResponse(unittest.TestCase):
    """AssetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetResponse:
        """Test AssetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetResponse`
        """
        model = AssetResponse()
        if include_optional:
            return AssetResponse(
                asset_type = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user_id = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                linked_models = [
                    inoue_ai_sdk.models.asset_linked_model.AssetLinkedModel(
                        id = '', 
                        name = '', )
                    ],
                metadata_json = None,
                origin_type = '',
                owner_email = '',
                owner_org_id = '',
                owner_user_id = '',
                public_url = '',
                storage_key = '',
                storage_pod_id = '',
                storage_region = '',
                storage_url = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AssetResponse(
                asset_type = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by_user_id = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                origin_type = '',
                owner_email = '',
                owner_org_id = '',
                owner_user_id = '',
                public_url = '',
                storage_key = '',
                storage_pod_id = '',
                storage_region = '',
                storage_url = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAssetResponse(self):
        """Test AssetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
