# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.api.collections_api import CollectionsApi


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_add_collection_item(self) -> None:
        """Test case for add_collection_item

        Add an item to a collection
        """
        pass

    def test_create_collection(self) -> None:
        """Test case for create_collection

        Create a collection
        """
        pass

    def test_delete_collection(self) -> None:
        """Test case for delete_collection

        Soft-delete a collection
        """
        pass

    def test_get_collection(self) -> None:
        """Test case for get_collection

        Get a single collection by id (with items)
        """
        pass

    def test_link_collection(self) -> None:
        """Test case for link_collection

        Link a collection to a model
        """
        pass

    def test_list_collection_items(self) -> None:
        """Test case for list_collection_items

        List the items in a collection
        """
        pass

    def test_list_collection_shares(self) -> None:
        """Test case for list_collection_shares

        List the access grants for a collection
        """
        pass

    def test_list_collections(self) -> None:
        """Test case for list_collections

        List the collections accessible to the caller (offset paginated)
        """
        pass

    def test_read_collection_item_secret(self) -> None:
        """Test case for read_collection_item_secret

        Read a collection item's stored secret
        """
        pass

    def test_remove_collection_item(self) -> None:
        """Test case for remove_collection_item

        Remove a collection item
        """
        pass

    def test_revoke_collection_share(self) -> None:
        """Test case for revoke_collection_share

        Revoke a collection access grant
        """
        pass

    def test_share_collection(self) -> None:
        """Test case for share_collection

        Grant access to a collection
        """
        pass

    def test_unlink_collection(self) -> None:
        """Test case for unlink_collection

        Unlink a collection from a model
        """
        pass

    def test_update_collection(self) -> None:
        """Test case for update_collection

        Update a collection
        """
        pass

    def test_update_collection_item(self) -> None:
        """Test case for update_collection_item

        Update a collection item
        """
        pass


if __name__ == '__main__':
    unittest.main()
