# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.video_job_link import VideoJobLink

class TestVideoJobLink(unittest.TestCase):
    """VideoJobLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VideoJobLink:
        """Test VideoJobLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VideoJobLink`
        """
        model = VideoJobLink()
        if include_optional:
            return VideoJobLink(
                id = '',
                job_id = '',
                job_status = '',
                job_type = '',
                linked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                linked_by_user_id = '',
                model_id = '',
                note = ''
            )
        else:
            return VideoJobLink(
                id = '',
                job_id = '',
                linked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                linked_by_user_id = '',
                model_id = '',
        )
        """

    def testVideoJobLink(self):
        """Test VideoJobLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
