# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_step_response import SuccessStepResponse

class TestSuccessStepResponse(unittest.TestCase):
    """SuccessStepResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessStepResponse:
        """Test SuccessStepResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessStepResponse`
        """
        model = SuccessStepResponse()
        if include_optional:
            return SuccessStepResponse(
                data = inoue_ai_sdk.models.step_response.StepResponse(
                    engine_slug = '', 
                    error = '', 
                    finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    id = '', 
                    inputs = null, 
                    job_id = '', 
                    job_type = '', 
                    node_id = '', 
                    node_label = '', 
                    output_asset_ids = [
                        ''
                        ], 
                    outputs = null, 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = '', ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessStepResponse(
                data = inoue_ai_sdk.models.step_response.StepResponse(
                    engine_slug = '', 
                    error = '', 
                    finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    id = '', 
                    inputs = null, 
                    job_id = '', 
                    job_type = '', 
                    node_id = '', 
                    node_label = '', 
                    output_asset_ids = [
                        ''
                        ], 
                    outputs = null, 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = '', ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessStepResponse(self):
        """Test SuccessStepResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
