# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_album_item_detail import SuccessAlbumItemDetail

class TestSuccessAlbumItemDetail(unittest.TestCase):
    """SuccessAlbumItemDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessAlbumItemDetail:
        """Test SuccessAlbumItemDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessAlbumItemDetail`
        """
        model = SuccessAlbumItemDetail()
        if include_optional:
            return SuccessAlbumItemDetail(
                data = inoue_ai_sdk.models.item_response.ItemResponse(
                    album_id = '', 
                    asset_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    has_password = True, 
                    id = '', 
                    item_type = '', 
                    metadata_json = null, 
                    note_text = '', 
                    password = '', 
                    title = '', 
                    url = '', 
                    username = '', ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessAlbumItemDetail(
                data = inoue_ai_sdk.models.item_response.ItemResponse(
                    album_id = '', 
                    asset_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    has_password = True, 
                    id = '', 
                    item_type = '', 
                    metadata_json = null, 
                    note_text = '', 
                    password = '', 
                    title = '', 
                    url = '', 
                    username = '', ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessAlbumItemDetail(self):
        """Test SuccessAlbumItemDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
