# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.api.push_subscriptions_api import PushSubscriptionsApi


class TestPushSubscriptionsApi(unittest.TestCase):
    """PushSubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PushSubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_get_vapid_public_key(self) -> None:
        """Test case for get_vapid_public_key

        Get the Web Push VAPID public key
        """
        pass

    def test_list_push_subscriptions(self) -> None:
        """Test case for list_push_subscriptions

        List the caller's Web Push subscriptions
        """
        pass

    def test_subscribe_push(self) -> None:
        """Test case for subscribe_push

        Register a Web Push subscription
        """
        pass

    def test_unsubscribe_push(self) -> None:
        """Test case for unsubscribe_push

        Unregister a Web Push subscription
        """
        pass


if __name__ == '__main__':
    unittest.main()
