# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.api.client_apps_api import ClientAppsApi


class TestClientAppsApi(unittest.TestCase):
    """ClientAppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClientAppsApi()

    def tearDown(self) -> None:
        pass

    def test_get_client_app_access(self) -> None:
        """Test case for get_client_app_access

        Check a client application's access for the caller
        """
        pass


if __name__ == '__main__':
    unittest.main()
