# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.candidates_payload import CandidatesPayload

class TestCandidatesPayload(unittest.TestCase):
    """CandidatesPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CandidatesPayload:
        """Test CandidatesPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CandidatesPayload`
        """
        model = CandidatesPayload()
        if include_optional:
            return CandidatesPayload(
                items = [
                    inoue_ai_sdk.models.model_candidate_response.ModelCandidateResponse(
                        body_image_url = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        face_image_url = '', 
                        id = '', 
                        index = 56, 
                        model_id = '', 
                        provenance = null, )
                    ]
            )
        else:
            return CandidatesPayload(
                items = [
                    inoue_ai_sdk.models.model_candidate_response.ModelCandidateResponse(
                        body_image_url = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        face_image_url = '', 
                        id = '', 
                        index = 56, 
                        model_id = '', 
                        provenance = null, )
                    ],
        )
        """

    def testCandidatesPayload(self):
        """Test CandidatesPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
