# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.page_order import PageOrder

class TestPageOrder(unittest.TestCase):
    """PageOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageOrder:
        """Test PageOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageOrder`
        """
        model = PageOrder()
        if include_optional:
            return PageOrder(
                items = [
                    inoue_ai_sdk.models.order.Order(
                        amount_subtotal_cents = 56, 
                        amount_total_cents = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        credits_amount = '', 
                        currency = '', 
                        id = '', 
                        order_type = '', 
                        status = '', 
                        stripe_checkout_session_id = '', 
                        stripe_invoice_id = '', 
                        stripe_payment_intent_id = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PageOrder(
                items = [
                    inoue_ai_sdk.models.order.Order(
                        amount_subtotal_cents = 56, 
                        amount_total_cents = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        credits_amount = '', 
                        currency = '', 
                        id = '', 
                        order_type = '', 
                        status = '', 
                        stripe_checkout_session_id = '', 
                        stripe_invoice_id = '', 
                        stripe_payment_intent_id = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPageOrder(self):
        """Test PageOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
