# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.org_overview_response import OrgOverviewResponse

class TestOrgOverviewResponse(unittest.TestCase):
    """OrgOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgOverviewResponse:
        """Test OrgOverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgOverviewResponse`
        """
        model = OrgOverviewResponse()
        if include_optional:
            return OrgOverviewResponse(
                audits = [
                    inoue_ai_sdk.models.org_overview_audit.OrgOverviewAudit(
                        action = '', 
                        actor = '', 
                        at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        trace_id = '', )
                    ],
                members = [
                    inoue_ai_sdk.models.org_overview_member.OrgOverviewMember(
                        id = '', 
                        name = '', 
                        role = '', 
                        status = '', )
                    ]
            )
        else:
            return OrgOverviewResponse(
                audits = [
                    inoue_ai_sdk.models.org_overview_audit.OrgOverviewAudit(
                        action = '', 
                        actor = '', 
                        at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        trace_id = '', )
                    ],
                members = [
                    inoue_ai_sdk.models.org_overview_member.OrgOverviewMember(
                        id = '', 
                        name = '', 
                        role = '', 
                        status = '', )
                    ],
        )
        """

    def testOrgOverviewResponse(self):
        """Test OrgOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
