# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_page_workflow_response import SuccessPageWorkflowResponse

class TestSuccessPageWorkflowResponse(unittest.TestCase):
    """SuccessPageWorkflowResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessPageWorkflowResponse:
        """Test SuccessPageWorkflowResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessPageWorkflowResponse`
        """
        model = SuccessPageWorkflowResponse()
        if include_optional:
            return SuccessPageWorkflowResponse(
                data = inoue_ai_sdk.models.page_workflow_response.PageWorkflowResponse(
                    items = [
                        inoue_ai_sdk.models.workflow_response.WorkflowResponse(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            description = '', 
                            engine_slugs = [
                                ''
                                ], 
                            id = '', 
                            last_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            name = '', 
                            owner_org_id = '', 
                            owner_user_id = '', 
                            run_count = 56, 
                            status = '', 
                            tags = [
                                ''
                                ], 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            version = 56, )
                        ], ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessPageWorkflowResponse(
                data = inoue_ai_sdk.models.page_workflow_response.PageWorkflowResponse(
                    items = [
                        inoue_ai_sdk.models.workflow_response.WorkflowResponse(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            description = '', 
                            engine_slugs = [
                                ''
                                ], 
                            id = '', 
                            last_run_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            name = '', 
                            owner_org_id = '', 
                            owner_user_id = '', 
                            run_count = 56, 
                            status = '', 
                            tags = [
                                ''
                                ], 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            version = 56, )
                        ], ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessPageWorkflowResponse(self):
        """Test SuccessPageWorkflowResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
