# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_list_asset_public_response import SuccessListAssetPublicResponse

class TestSuccessListAssetPublicResponse(unittest.TestCase):
    """SuccessListAssetPublicResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessListAssetPublicResponse:
        """Test SuccessListAssetPublicResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessListAssetPublicResponse`
        """
        model = SuccessListAssetPublicResponse()
        if include_optional:
            return SuccessListAssetPublicResponse(
                data = [
                    inoue_ai_sdk.models.asset_public_response.AssetPublicResponse(
                        asset_type = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        metadata_json = null, 
                        origin_type = '', 
                        owner_org_id = '', 
                        owner_user_id = '', 
                        storage_key = '', 
                        storage_pod_id = '', 
                        storage_region = '', 
                        storage_url = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessListAssetPublicResponse(
                data = [
                    inoue_ai_sdk.models.asset_public_response.AssetPublicResponse(
                        asset_type = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        metadata_json = null, 
                        origin_type = '', 
                        owner_org_id = '', 
                        owner_user_id = '', 
                        storage_key = '', 
                        storage_pod_id = '', 
                        storage_region = '', 
                        storage_url = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessListAssetPublicResponse(self):
        """Test SuccessListAssetPublicResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
