# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.civitai_key_revoke_body import CivitaiKeyRevokeBody

class TestCivitaiKeyRevokeBody(unittest.TestCase):
    """CivitaiKeyRevokeBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CivitaiKeyRevokeBody:
        """Test CivitaiKeyRevokeBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CivitaiKeyRevokeBody`
        """
        model = CivitaiKeyRevokeBody()
        if include_optional:
            return CivitaiKeyRevokeBody(
                grant_id = '',
                share_id = ''
            )
        else:
            return CivitaiKeyRevokeBody(
        )
        """

    def testCivitaiKeyRevokeBody(self):
        """Test CivitaiKeyRevokeBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
