# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.nano_banana_options import NanoBananaOptions

class TestNanoBananaOptions(unittest.TestCase):
    """NanoBananaOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NanoBananaOptions:
        """Test NanoBananaOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NanoBananaOptions`
        """
        model = NanoBananaOptions()
        if include_optional:
            return NanoBananaOptions(
                aspect_ratios = [
                    ''
                    ],
                default_num_images = 56,
                max_num_images = 56,
                max_reference_images = 56,
                pro_resolutions = [
                    ''
                    ],
                sizes = [
                    ''
                    ]
            )
        else:
            return NanoBananaOptions(
                aspect_ratios = [
                    ''
                    ],
                default_num_images = 56,
                max_num_images = 56,
                max_reference_images = 56,
                pro_resolutions = [
                    ''
                    ],
                sizes = [
                    ''
                    ],
        )
        """

    def testNanoBananaOptions(self):
        """Test NanoBananaOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
