# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.integration_webhook_list_response import IntegrationWebhookListResponse

class TestIntegrationWebhookListResponse(unittest.TestCase):
    """IntegrationWebhookListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationWebhookListResponse:
        """Test IntegrationWebhookListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationWebhookListResponse`
        """
        model = IntegrationWebhookListResponse()
        if include_optional:
            return IntegrationWebhookListResponse(
                items = [
                    inoue_ai_sdk.models.webhook_response.WebhookResponse(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        event_types = [
                            ''
                            ], 
                        has_secret = True, 
                        id = '', 
                        is_enabled = True, 
                        name = '', 
                        org_id = '', 
                        owner_user_id = '', 
                        scope = '', 
                        secret_hint = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        url = '', )
                    ],
                total = 56
            )
        else:
            return IntegrationWebhookListResponse(
                items = [
                    inoue_ai_sdk.models.webhook_response.WebhookResponse(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by_user_id = '', 
                        event_types = [
                            ''
                            ], 
                        has_secret = True, 
                        id = '', 
                        is_enabled = True, 
                        name = '', 
                        org_id = '', 
                        owner_user_id = '', 
                        scope = '', 
                        secret_hint = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        url = '', )
                    ],
                total = 56,
        )
        """

    def testIntegrationWebhookListResponse(self):
        """Test IntegrationWebhookListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
