# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.success_membership_response import SuccessMembershipResponse

class TestSuccessMembershipResponse(unittest.TestCase):
    """SuccessMembershipResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessMembershipResponse:
        """Test SuccessMembershipResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessMembershipResponse`
        """
        model = SuccessMembershipResponse()
        if include_optional:
            return SuccessMembershipResponse(
                data = inoue_ai_sdk.models.membership_response.MembershipResponse(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email = '', 
                    id = '', 
                    name = '', 
                    org_id = '', 
                    role = '', 
                    status = '', 
                    user_id = '', ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True
            )
        else:
            return SuccessMembershipResponse(
                data = inoue_ai_sdk.models.membership_response.MembershipResponse(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email = '', 
                    id = '', 
                    name = '', 
                    org_id = '', 
                    role = '', 
                    status = '', 
                    user_id = '', ),
                meta = inoue_ai_sdk.models.meta.Meta(
                    pagination = inoue_ai_sdk.models.pagination.Pagination(
                        page = 56, 
                        page_size = 56, 
                        total = 56, ), 
                    request_id = '', 
                    trace_id = '', 
                    version = '', ),
                ok = True,
        )
        """

    def testSuccessMembershipResponse(self):
        """Test SuccessMembershipResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
