# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.document import Document

class TestDocument(unittest.TestCase):
    """Document unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Document:
        """Test Document
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Document`
        """
        model = Document()
        if include_optional:
            return Document(
                effective_date = '',
                key = '',
                sections = [
                    inoue_ai_sdk.models.section.Section(
                        body = [
                            ''
                            ], 
                        heading = '', )
                    ],
                summary = '',
                title = '',
                version = ''
            )
        else:
            return Document(
                effective_date = '',
                key = '',
                sections = [
                    inoue_ai_sdk.models.section.Section(
                        body = [
                            ''
                            ], 
                        heading = '', )
                    ],
                summary = '',
                title = '',
                version = '',
        )
        """

    def testDocument(self):
        """Test Document"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
