# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inoue_ai_sdk.models.workflow_batch_run_response import WorkflowBatchRunResponse

class TestWorkflowBatchRunResponse(unittest.TestCase):
    """WorkflowBatchRunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowBatchRunResponse:
        """Test WorkflowBatchRunResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowBatchRunResponse`
        """
        model = WorkflowBatchRunResponse()
        if include_optional:
            return WorkflowBatchRunResponse(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                input_matrix = None,
                runs = [
                    inoue_ai_sdk.models.workflow_run_response.WorkflowRunResponse(
                        batch_index = 56, 
                        batch_run_id = '', 
                        batch_total = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error = '', 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        inputs = null, 
                        status = '', 
                        steps = [
                            inoue_ai_sdk.models.workflow_run_step_response.WorkflowRunStepResponse(
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                engine_slug = '', 
                                error = '', 
                                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                id = '', 
                                inputs = null, 
                                job_id = '', 
                                job_type = '', 
                                node_id = '', 
                                node_label = '', 
                                output_asset_ids = [
                                    ''
                                    ], 
                                outputs = null, 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                status = '', 
                                workflow_run_id = '', )
                            ], 
                        total_cost = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        workflow_id = '', 
                        workflow_name = '', )
                    ],
                status = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                workflow_id = ''
            )
        else:
            return WorkflowBatchRunResponse(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                input_matrix = None,
                runs = [
                    inoue_ai_sdk.models.workflow_run_response.WorkflowRunResponse(
                        batch_index = 56, 
                        batch_run_id = '', 
                        batch_total = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        error = '', 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        inputs = null, 
                        status = '', 
                        steps = [
                            inoue_ai_sdk.models.workflow_run_step_response.WorkflowRunStepResponse(
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                engine_slug = '', 
                                error = '', 
                                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                id = '', 
                                inputs = null, 
                                job_id = '', 
                                job_type = '', 
                                node_id = '', 
                                node_label = '', 
                                output_asset_ids = [
                                    ''
                                    ], 
                                outputs = null, 
                                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                status = '', 
                                workflow_run_id = '', )
                            ], 
                        total_cost = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        workflow_id = '', 
                        workflow_name = '', )
                    ],
                status = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                workflow_id = '',
        )
        """

    def testWorkflowBatchRunResponse(self):
        """Test WorkflowBatchRunResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
