/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumLinkBody
 */
export interface AlbumLinkBody {
    /**
     * 
     * @type {string}
     * @memberof AlbumLinkBody
     */
    albumId: string;
    /**
     * 
     * @type {string}
     * @memberof AlbumLinkBody
     */
    modelId: string;
}

/**
 * Check if a given object implements the AlbumLinkBody interface.
 */
export function instanceOfAlbumLinkBody(value: object): value is AlbumLinkBody {
    if (!('albumId' in value) || value['albumId'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    return true;
}

export function AlbumLinkBodyFromJSON(json: any): AlbumLinkBody {
    return AlbumLinkBodyFromJSONTyped(json, false);
}

export function AlbumLinkBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumLinkBody {
    if (json == null) {
        return json;
    }
    return {
        
        'albumId': json['album_id'],
        'modelId': json['model_id'],
    };
}

export function AlbumLinkBodyToJSON(json: any): AlbumLinkBody {
    return AlbumLinkBodyToJSONTyped(json, false);
}

export function AlbumLinkBodyToJSONTyped(value?: AlbumLinkBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'album_id': value['albumId'],
        'model_id': value['modelId'],
    };
}

