/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetIDBody
 */
export interface AssetIDBody {
    /**
     * 
     * @type {string}
     * @memberof AssetIDBody
     */
    assetId: string;
}

/**
 * Check if a given object implements the AssetIDBody interface.
 */
export function instanceOfAssetIDBody(value: object): value is AssetIDBody {
    if (!('assetId' in value) || value['assetId'] === undefined) return false;
    return true;
}

export function AssetIDBodyFromJSON(json: any): AssetIDBody {
    return AssetIDBodyFromJSONTyped(json, false);
}

export function AssetIDBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetIDBody {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['asset_id'],
    };
}

export function AssetIDBodyToJSON(json: any): AssetIDBody {
    return AssetIDBodyToJSONTyped(json, false);
}

export function AssetIDBodyToJSONTyped(value?: AssetIDBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset_id': value['assetId'],
    };
}

