/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetUploadBody
 */
export interface AssetUploadBody {
    /**
     * 
     * @type {string}
     * @memberof AssetUploadBody
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof AssetUploadBody
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof AssetUploadBody
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetUploadBody
     */
    ownerOrgId?: string;
    /**
     * 
     * @type {number}
     * @memberof AssetUploadBody
     */
    sizeBytes: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AssetUploadBody
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AssetUploadBody
     */
    title?: string;
}

/**
 * Check if a given object implements the AssetUploadBody interface.
 */
export function instanceOfAssetUploadBody(value: object): value is AssetUploadBody {
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    return true;
}

export function AssetUploadBodyFromJSON(json: any): AssetUploadBody {
    return AssetUploadBodyFromJSONTyped(json, false);
}

export function AssetUploadBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetUploadBody {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['content_type'],
        'filename': json['filename'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'ownerOrgId': json['owner_org_id'] == null ? undefined : json['owner_org_id'],
        'sizeBytes': json['size_bytes'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function AssetUploadBodyToJSON(json: any): AssetUploadBody {
    return AssetUploadBodyToJSONTyped(json, false);
}

export function AssetUploadBodyToJSONTyped(value?: AssetUploadBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': value['contentType'],
        'filename': value['filename'],
        'notes': value['notes'],
        'owner_org_id': value['ownerOrgId'],
        'size_bytes': value['sizeBytes'],
        'tags': value['tags'],
        'title': value['title'],
    };
}

