/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvatarProfileCreateBody
 */
export interface AvatarProfileCreateBody {
    /**
     * 
     * @type {any}
     * @memberof AvatarProfileCreateBody
     */
    config?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AvatarProfileCreateBody
     */
    modelId: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarProfileCreateBody
     */
    name: string;
}

/**
 * Check if a given object implements the AvatarProfileCreateBody interface.
 */
export function instanceOfAvatarProfileCreateBody(value: object): value is AvatarProfileCreateBody {
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AvatarProfileCreateBodyFromJSON(json: any): AvatarProfileCreateBody {
    return AvatarProfileCreateBodyFromJSONTyped(json, false);
}

export function AvatarProfileCreateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarProfileCreateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
        'modelId': json['model_id'],
        'name': json['name'],
    };
}

export function AvatarProfileCreateBodyToJSON(json: any): AvatarProfileCreateBody {
    return AvatarProfileCreateBodyToJSONTyped(json, false);
}

export function AvatarProfileCreateBodyToJSONTyped(value?: AvatarProfileCreateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'model_id': value['modelId'],
        'name': value['name'],
    };
}

