/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchRunRequest
 */
export interface BatchRunRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof BatchRunRequest
     */
    concurrency?: number;
    /**
     * 
     * @type {Array<Array<object>>}
     * @memberof BatchRunRequest
     */
    inputMatrix: Array<Array<object>>;
    /**
     * 
     * @type {string}
     * @memberof BatchRunRequest
     */
    ownerOrgId?: string;
}

/**
 * Check if a given object implements the BatchRunRequest interface.
 */
export function instanceOfBatchRunRequest(value: object): value is BatchRunRequest {
    if (!('inputMatrix' in value) || value['inputMatrix'] === undefined) return false;
    return true;
}

export function BatchRunRequestFromJSON(json: any): BatchRunRequest {
    return BatchRunRequestFromJSONTyped(json, false);
}

export function BatchRunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchRunRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'concurrency': json['concurrency'] == null ? undefined : json['concurrency'],
        'inputMatrix': json['input_matrix'],
        'ownerOrgId': json['owner_org_id'] == null ? undefined : json['owner_org_id'],
    };
}

export function BatchRunRequestToJSON(json: any): BatchRunRequest {
    return BatchRunRequestToJSONTyped(json, false);
}

export function BatchRunRequestToJSONTyped(value?: BatchRunRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'concurrency': value['concurrency'],
        'input_matrix': value['inputMatrix'],
        'owner_org_id': value['ownerOrgId'],
    };
}

