/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CaptionTemplateDeletionRes
 */
export interface CaptionTemplateDeletionRes {
    /**
     * 
     * @type {boolean}
     * @memberof CaptionTemplateDeletionRes
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the CaptionTemplateDeletionRes interface.
 */
export function instanceOfCaptionTemplateDeletionRes(value: object): value is CaptionTemplateDeletionRes {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function CaptionTemplateDeletionResFromJSON(json: any): CaptionTemplateDeletionRes {
    return CaptionTemplateDeletionResFromJSONTyped(json, false);
}

export function CaptionTemplateDeletionResFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptionTemplateDeletionRes {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function CaptionTemplateDeletionResToJSON(json: any): CaptionTemplateDeletionRes {
    return CaptionTemplateDeletionResToJSONTyped(json, false);
}

export function CaptionTemplateDeletionResToJSONTyped(value?: CaptionTemplateDeletionRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

