/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CivitaiKeyItem
 */
export interface CivitaiKeyItem {
    /**
     * 
     * @type {string}
     * @memberof CivitaiKeyItem
     */
    accessLevel: string;
    /**
     * 
     * @type {boolean}
     * @memberof CivitaiKeyItem
     */
    canManage: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CivitaiKeyItem
     */
    createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CivitaiKeyItem
     */
    createdByUserId: string;
    /**
     * 
     * @type {string}
     * @memberof CivitaiKeyItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CivitaiKeyItem
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof CivitaiKeyItem
     */
    last4: string | null;
    /**
     * 
     * @type {string}
     * @memberof CivitaiKeyItem
     */
    ownerUserId: string;
    /**
     * 
     * @type {Date}
     * @memberof CivitaiKeyItem
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the CivitaiKeyItem interface.
 */
export function instanceOfCivitaiKeyItem(value: object): value is CivitaiKeyItem {
    if (!('accessLevel' in value) || value['accessLevel'] === undefined) return false;
    if (!('canManage' in value) || value['canManage'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdByUserId' in value) || value['createdByUserId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('last4' in value) || value['last4'] === undefined) return false;
    if (!('ownerUserId' in value) || value['ownerUserId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CivitaiKeyItemFromJSON(json: any): CivitaiKeyItem {
    return CivitaiKeyItemFromJSONTyped(json, false);
}

export function CivitaiKeyItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CivitaiKeyItem {
    if (json == null) {
        return json;
    }
    return {
        
        'accessLevel': json['access_level'],
        'canManage': json['can_manage'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'createdByUserId': json['created_by_user_id'],
        'id': json['id'],
        'label': json['label'],
        'last4': json['last4'],
        'ownerUserId': json['owner_user_id'],
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
    };
}

export function CivitaiKeyItemToJSON(json: any): CivitaiKeyItem {
    return CivitaiKeyItemToJSONTyped(json, false);
}

export function CivitaiKeyItemToJSONTyped(value?: CivitaiKeyItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_level': value['accessLevel'],
        'can_manage': value['canManage'],
        'created_at': (value['createdAt'] == null ? null : (value['createdAt'] as any).toISOString()),
        'created_by_user_id': value['createdByUserId'],
        'id': value['id'],
        'label': value['label'],
        'last4': value['last4'],
        'owner_user_id': value['ownerUserId'],
        'updated_at': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

