/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionItemUpdateBody
 */
export interface CollectionItemUpdateBody {
    /**
     * 
     * @type {any}
     * @memberof CollectionItemUpdateBody
     */
    assetId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionItemUpdateBody
     */
    collectionId?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionItemUpdateBody
     */
    itemType?: string;
    /**
     * 
     * @type {any}
     * @memberof CollectionItemUpdateBody
     */
    metadataJson?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CollectionItemUpdateBody
     */
    noteText?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CollectionItemUpdateBody
     */
    password?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CollectionItemUpdateBody
     */
    title?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CollectionItemUpdateBody
     */
    url?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CollectionItemUpdateBody
     */
    username?: any | null;
}

/**
 * Check if a given object implements the CollectionItemUpdateBody interface.
 */
export function instanceOfCollectionItemUpdateBody(value: object): value is CollectionItemUpdateBody {
    return true;
}

export function CollectionItemUpdateBodyFromJSON(json: any): CollectionItemUpdateBody {
    return CollectionItemUpdateBodyFromJSONTyped(json, false);
}

export function CollectionItemUpdateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionItemUpdateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'assetId': json['asset_id'] == null ? undefined : json['asset_id'],
        'collectionId': json['collection_id'] == null ? undefined : json['collection_id'],
        'itemType': json['item_type'] == null ? undefined : json['item_type'],
        'metadataJson': json['metadata_json'] == null ? undefined : json['metadata_json'],
        'noteText': json['note_text'] == null ? undefined : json['note_text'],
        'password': json['password'] == null ? undefined : json['password'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function CollectionItemUpdateBodyToJSON(json: any): CollectionItemUpdateBody {
    return CollectionItemUpdateBodyToJSONTyped(json, false);
}

export function CollectionItemUpdateBodyToJSONTyped(value?: CollectionItemUpdateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset_id': value['assetId'],
        'collection_id': value['collectionId'],
        'item_type': value['itemType'],
        'metadata_json': value['metadataJson'],
        'note_text': value['noteText'],
        'password': value['password'],
        'title': value['title'],
        'url': value['url'],
        'username': value['username'],
    };
}

