/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatedWebhookResponse
 */
export interface CreatedWebhookResponse {
    /**
     * 
     * @type {Date}
     * @memberof CreatedWebhookResponse
     */
    createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    createdByUserId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreatedWebhookResponse
     */
    eventTypes: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreatedWebhookResponse
     */
    hasSecret: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreatedWebhookResponse
     */
    isEnabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    ownerUserId: string;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    secret?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    secretHint?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatedWebhookResponse
     */
    updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof CreatedWebhookResponse
     */
    url: string;
}

/**
 * Check if a given object implements the CreatedWebhookResponse interface.
 */
export function instanceOfCreatedWebhookResponse(value: object): value is CreatedWebhookResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdByUserId' in value) || value['createdByUserId'] === undefined) return false;
    if (!('eventTypes' in value) || value['eventTypes'] === undefined) return false;
    if (!('hasSecret' in value) || value['hasSecret'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isEnabled' in value) || value['isEnabled'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('ownerUserId' in value) || value['ownerUserId'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreatedWebhookResponseFromJSON(json: any): CreatedWebhookResponse {
    return CreatedWebhookResponseFromJSONTyped(json, false);
}

export function CreatedWebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedWebhookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'createdByUserId': json['created_by_user_id'],
        'eventTypes': json['event_types'] == null ? null : json['event_types'],
        'hasSecret': json['has_secret'],
        'id': json['id'],
        'isEnabled': json['is_enabled'],
        'name': json['name'],
        'orgId': json['org_id'],
        'ownerUserId': json['owner_user_id'],
        'scope': json['scope'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'secretHint': json['secret_hint'] == null ? undefined : json['secret_hint'],
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
        'url': json['url'],
    };
}

export function CreatedWebhookResponseToJSON(json: any): CreatedWebhookResponse {
    return CreatedWebhookResponseToJSONTyped(json, false);
}

export function CreatedWebhookResponseToJSONTyped(value?: CreatedWebhookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': (value['createdAt'] == null ? null : (value['createdAt'] as any).toISOString()),
        'created_by_user_id': value['createdByUserId'],
        'event_types': value['eventTypes'],
        'has_secret': value['hasSecret'],
        'id': value['id'],
        'is_enabled': value['isEnabled'],
        'name': value['name'],
        'org_id': value['orgId'],
        'owner_user_id': value['ownerUserId'],
        'scope': value['scope'],
        'secret': value['secret'],
        'secret_hint': value['secretHint'],
        'updated_at': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
        'url': value['url'],
    };
}

