/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CursorPagination } from './CursorPagination';
import {
    CursorPaginationFromJSON,
    CursorPaginationFromJSONTyped,
    CursorPaginationToJSON,
    CursorPaginationToJSONTyped,
} from './CursorPagination';

/**
 * 
 * @export
 * @interface CursorMeta
 */
export interface CursorMeta {
    /**
     * 
     * @type {CursorPagination}
     * @memberof CursorMeta
     */
    pagination?: CursorPagination;
    /**
     * 
     * @type {string}
     * @memberof CursorMeta
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof CursorMeta
     */
    traceId: string;
    /**
     * 
     * @type {string}
     * @memberof CursorMeta
     */
    version: string;
}

/**
 * Check if a given object implements the CursorMeta interface.
 */
export function instanceOfCursorMeta(value: object): value is CursorMeta {
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function CursorMetaFromJSON(json: any): CursorMeta {
    return CursorMetaFromJSONTyped(json, false);
}

export function CursorMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : CursorPaginationFromJSON(json['pagination']),
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'traceId': json['trace_id'],
        'version': json['version'],
    };
}

export function CursorMetaToJSON(json: any): CursorMeta {
    return CursorMetaToJSONTyped(json, false);
}

export function CursorMetaToJSONTyped(value?: CursorMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': CursorPaginationToJSON(value['pagination']),
        'request_id': value['requestId'],
        'trace_id': value['traceId'],
        'version': value['version'],
    };
}

