/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationWebhookCreateBody
 */
export interface IntegrationWebhookCreateBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof IntegrationWebhookCreateBody
     */
    eventTypes?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof IntegrationWebhookCreateBody
     */
    isEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IntegrationWebhookCreateBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationWebhookCreateBody
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationWebhookCreateBody
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationWebhookCreateBody
     */
    url: string;
}

/**
 * Check if a given object implements the IntegrationWebhookCreateBody interface.
 */
export function instanceOfIntegrationWebhookCreateBody(value: object): value is IntegrationWebhookCreateBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function IntegrationWebhookCreateBodyFromJSON(json: any): IntegrationWebhookCreateBody {
    return IntegrationWebhookCreateBodyFromJSONTyped(json, false);
}

export function IntegrationWebhookCreateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationWebhookCreateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'eventTypes': json['event_types'] == null ? undefined : json['event_types'],
        'isEnabled': json['is_enabled'] == null ? undefined : json['is_enabled'],
        'name': json['name'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'url': json['url'],
    };
}

export function IntegrationWebhookCreateBodyToJSON(json: any): IntegrationWebhookCreateBody {
    return IntegrationWebhookCreateBodyToJSONTyped(json, false);
}

export function IntegrationWebhookCreateBodyToJSONTyped(value?: IntegrationWebhookCreateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_types': value['eventTypes'],
        'is_enabled': value['isEnabled'],
        'name': value['name'],
        'org_id': value['orgId'],
        'scope': value['scope'],
        'url': value['url'],
    };
}

