/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KlingRequestBody
 */
export interface KlingRequestBody {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    aspectRatio: string;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    audioUrl: string;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    backgroundSource: string;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    characterOrientation: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KlingRequestBody
     */
    imageUrls?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    jobType: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof KlingRequestBody
     */
    klingElements?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof KlingRequestBody
     */
    lengthSeconds: number;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    mode: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof KlingRequestBody
     */
    multiPrompt?: Array<object>;
    /**
     * 
     * @type {boolean}
     * @memberof KlingRequestBody
     */
    multiShots: boolean;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    prompt: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof KlingRequestBody
     */
    referenceAssetIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KlingRequestBody
     */
    referenceVideoAssetId: string;
    /**
     * 
     * @type {boolean}
     * @memberof KlingRequestBody
     */
    sound: boolean;
}

/**
 * Check if a given object implements the KlingRequestBody interface.
 */
export function instanceOfKlingRequestBody(value: object): value is KlingRequestBody {
    if (!('aspectRatio' in value) || value['aspectRatio'] === undefined) return false;
    if (!('audioUrl' in value) || value['audioUrl'] === undefined) return false;
    if (!('backgroundSource' in value) || value['backgroundSource'] === undefined) return false;
    if (!('characterOrientation' in value) || value['characterOrientation'] === undefined) return false;
    if (!('jobType' in value) || value['jobType'] === undefined) return false;
    if (!('lengthSeconds' in value) || value['lengthSeconds'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('multiShots' in value) || value['multiShots'] === undefined) return false;
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('referenceVideoAssetId' in value) || value['referenceVideoAssetId'] === undefined) return false;
    if (!('sound' in value) || value['sound'] === undefined) return false;
    return true;
}

export function KlingRequestBodyFromJSON(json: any): KlingRequestBody {
    return KlingRequestBodyFromJSONTyped(json, false);
}

export function KlingRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): KlingRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'aspectRatio': json['aspect_ratio'],
        'audioUrl': json['audio_url'],
        'backgroundSource': json['background_source'],
        'characterOrientation': json['character_orientation'],
        'imageUrls': json['image_urls'] == null ? undefined : json['image_urls'],
        'jobType': json['job_type'],
        'klingElements': json['kling_elements'] == null ? undefined : json['kling_elements'],
        'lengthSeconds': json['length_seconds'],
        'mode': json['mode'],
        'multiPrompt': json['multi_prompt'] == null ? undefined : json['multi_prompt'],
        'multiShots': json['multi_shots'],
        'prompt': json['prompt'],
        'referenceAssetIds': json['reference_asset_ids'] == null ? undefined : json['reference_asset_ids'],
        'referenceVideoAssetId': json['reference_video_asset_id'],
        'sound': json['sound'],
    };
}

export function KlingRequestBodyToJSON(json: any): KlingRequestBody {
    return KlingRequestBodyToJSONTyped(json, false);
}

export function KlingRequestBodyToJSONTyped(value?: KlingRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'aspect_ratio': value['aspectRatio'],
        'audio_url': value['audioUrl'],
        'background_source': value['backgroundSource'],
        'character_orientation': value['characterOrientation'],
        'image_urls': value['imageUrls'],
        'job_type': value['jobType'],
        'kling_elements': value['klingElements'],
        'length_seconds': value['lengthSeconds'],
        'mode': value['mode'],
        'multi_prompt': value['multiPrompt'],
        'multi_shots': value['multiShots'],
        'prompt': value['prompt'],
        'reference_asset_ids': value['referenceAssetIds'],
        'reference_video_asset_id': value['referenceVideoAssetId'],
        'sound': value['sound'],
    };
}

