/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelTransferBody
 */
export interface ModelTransferBody {
    /**
     * 
     * @type {string}
     * @memberof ModelTransferBody
     */
    modelId: string;
    /**
     * 
     * @type {string}
     * @memberof ModelTransferBody
     */
    newOwnerOrgId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelTransferBody
     */
    newOwnerUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelTransferBody
     */
    targetId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelTransferBody
     */
    targetType?: string;
}

/**
 * Check if a given object implements the ModelTransferBody interface.
 */
export function instanceOfModelTransferBody(value: object): value is ModelTransferBody {
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    return true;
}

export function ModelTransferBodyFromJSON(json: any): ModelTransferBody {
    return ModelTransferBodyFromJSONTyped(json, false);
}

export function ModelTransferBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelTransferBody {
    if (json == null) {
        return json;
    }
    return {
        
        'modelId': json['model_id'],
        'newOwnerOrgId': json['new_owner_org_id'] == null ? undefined : json['new_owner_org_id'],
        'newOwnerUserId': json['new_owner_user_id'] == null ? undefined : json['new_owner_user_id'],
        'targetId': json['target_id'] == null ? undefined : json['target_id'],
        'targetType': json['target_type'] == null ? undefined : json['target_type'],
    };
}

export function ModelTransferBodyToJSON(json: any): ModelTransferBody {
    return ModelTransferBodyToJSONTyped(json, false);
}

export function ModelTransferBodyToJSONTyped(value?: ModelTransferBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model_id': value['modelId'],
        'new_owner_org_id': value['newOwnerOrgId'],
        'new_owner_user_id': value['newOwnerUserId'],
        'target_id': value['targetId'],
        'target_type': value['targetType'],
    };
}

