/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationDeletionRes
 */
export interface NotificationDeletionRes {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationDeletionRes
     */
    deleted: boolean;
}

/**
 * Check if a given object implements the NotificationDeletionRes interface.
 */
export function instanceOfNotificationDeletionRes(value: object): value is NotificationDeletionRes {
    if (!('deleted' in value) || value['deleted'] === undefined) return false;
    return true;
}

export function NotificationDeletionResFromJSON(json: any): NotificationDeletionRes {
    return NotificationDeletionResFromJSONTyped(json, false);
}

export function NotificationDeletionResFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDeletionRes {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'],
    };
}

export function NotificationDeletionResToJSON(json: any): NotificationDeletionRes {
    return NotificationDeletionResToJSONTyped(json, false);
}

export function NotificationDeletionResToJSONTyped(value?: NotificationDeletionRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

