/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationCreateBody
 */
export interface NotificationCreateBody {
    /**
     * 
     * @type {string}
     * @memberof NotificationCreateBody
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationCreateBody
     */
    modelId: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationCreateBody
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationCreateBody
     */
    title: string;
}

/**
 * Check if a given object implements the NotificationCreateBody interface.
 */
export function instanceOfNotificationCreateBody(value: object): value is NotificationCreateBody {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function NotificationCreateBodyFromJSON(json: any): NotificationCreateBody {
    return NotificationCreateBodyFromJSONTyped(json, false);
}

export function NotificationCreateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationCreateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'modelId': json['model_id'],
        'orgId': json['org_id'],
        'title': json['title'],
    };
}

export function NotificationCreateBodyToJSON(json: any): NotificationCreateBody {
    return NotificationCreateBodyToJSONTyped(json, false);
}

export function NotificationCreateBodyToJSONTyped(value?: NotificationCreateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'model_id': value['modelId'],
        'org_id': value['orgId'],
        'title': value['title'],
    };
}

