/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrgOverviewAudit } from './OrgOverviewAudit';
import {
    OrgOverviewAuditFromJSON,
    OrgOverviewAuditFromJSONTyped,
    OrgOverviewAuditToJSON,
    OrgOverviewAuditToJSONTyped,
} from './OrgOverviewAudit';
import type { OrgOverviewMember } from './OrgOverviewMember';
import {
    OrgOverviewMemberFromJSON,
    OrgOverviewMemberFromJSONTyped,
    OrgOverviewMemberToJSON,
    OrgOverviewMemberToJSONTyped,
} from './OrgOverviewMember';

/**
 * 
 * @export
 * @interface OrgOverviewResponse
 */
export interface OrgOverviewResponse {
    /**
     * 
     * @type {Array<OrgOverviewAudit>}
     * @memberof OrgOverviewResponse
     */
    audits: Array<OrgOverviewAudit> | null;
    /**
     * 
     * @type {Array<OrgOverviewMember>}
     * @memberof OrgOverviewResponse
     */
    members: Array<OrgOverviewMember> | null;
}

/**
 * Check if a given object implements the OrgOverviewResponse interface.
 */
export function instanceOfOrgOverviewResponse(value: object): value is OrgOverviewResponse {
    if (!('audits' in value) || value['audits'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    return true;
}

export function OrgOverviewResponseFromJSON(json: any): OrgOverviewResponse {
    return OrgOverviewResponseFromJSONTyped(json, false);
}

export function OrgOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'audits': (json['audits'] == null ? null : (json['audits'] as Array<any>).map(OrgOverviewAuditFromJSON)),
        'members': (json['members'] == null ? null : (json['members'] as Array<any>).map(OrgOverviewMemberFromJSON)),
    };
}

export function OrgOverviewResponseToJSON(json: any): OrgOverviewResponse {
    return OrgOverviewResponseToJSONTyped(json, false);
}

export function OrgOverviewResponseToJSONTyped(value?: OrgOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audits': (value['audits'] == null ? null : (value['audits'] as Array<any>).map(OrgOverviewAuditToJSON)),
        'members': (value['members'] == null ? null : (value['members'] as Array<any>).map(OrgOverviewMemberToJSON)),
    };
}

