/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgOverviewMember
 */
export interface OrgOverviewMember {
    /**
     * 
     * @type {string}
     * @memberof OrgOverviewMember
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrgOverviewMember
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrgOverviewMember
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof OrgOverviewMember
     */
    status: string;
}

/**
 * Check if a given object implements the OrgOverviewMember interface.
 */
export function instanceOfOrgOverviewMember(value: object): value is OrgOverviewMember {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrgOverviewMemberFromJSON(json: any): OrgOverviewMember {
    return OrgOverviewMemberFromJSONTyped(json, false);
}

export function OrgOverviewMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgOverviewMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'role': json['role'],
        'status': json['status'],
    };
}

export function OrgOverviewMemberToJSON(json: any): OrgOverviewMember {
    return OrgOverviewMemberToJSONTyped(json, false);
}

export function OrgOverviewMemberToJSONTyped(value?: OrgOverviewMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'role': value['role'],
        'status': value['status'],
    };
}

