/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgRemoveMemberBody
 */
export interface OrgRemoveMemberBody {
    /**
     * 
     * @type {string}
     * @memberof OrgRemoveMemberBody
     */
    memberId: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrgRemoveMemberBody
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof OrgRemoveMemberBody
     */
    userId: string | null;
}

/**
 * Check if a given object implements the OrgRemoveMemberBody interface.
 */
export function instanceOfOrgRemoveMemberBody(value: object): value is OrgRemoveMemberBody {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function OrgRemoveMemberBodyFromJSON(json: any): OrgRemoveMemberBody {
    return OrgRemoveMemberBodyFromJSONTyped(json, false);
}

export function OrgRemoveMemberBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgRemoveMemberBody {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['member_id'],
        'orgId': json['org_id'],
        'userId': json['user_id'],
    };
}

export function OrgRemoveMemberBodyToJSON(json: any): OrgRemoveMemberBody {
    return OrgRemoveMemberBodyToJSONTyped(json, false);
}

export function OrgRemoveMemberBodyToJSONTyped(value?: OrgRemoveMemberBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_id': value['memberId'],
        'org_id': value['orgId'],
        'user_id': value['userId'],
    };
}

