/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgUpdateBody
 */
export interface OrgUpdateBody {
    /**
     * 
     * @type {string}
     * @memberof OrgUpdateBody
     */
    iconUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgUpdateBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgUpdateBody
     */
    orgId: string;
}

/**
 * Check if a given object implements the OrgUpdateBody interface.
 */
export function instanceOfOrgUpdateBody(value: object): value is OrgUpdateBody {
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    return true;
}

export function OrgUpdateBodyFromJSON(json: any): OrgUpdateBody {
    return OrgUpdateBodyFromJSONTyped(json, false);
}

export function OrgUpdateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgUpdateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'name': json['name'] == null ? undefined : json['name'],
        'orgId': json['org_id'],
    };
}

export function OrgUpdateBodyToJSON(json: any): OrgUpdateBody {
    return OrgUpdateBodyToJSONTyped(json, false);
}

export function OrgUpdateBodyToJSONTyped(value?: OrgUpdateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icon_url': value['iconUrl'],
        'name': value['name'],
        'org_id': value['orgId'],
    };
}

