/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscordWebhookResponse } from './DiscordWebhookResponse';
import {
    DiscordWebhookResponseFromJSON,
    DiscordWebhookResponseFromJSONTyped,
    DiscordWebhookResponseToJSON,
    DiscordWebhookResponseToJSONTyped,
} from './DiscordWebhookResponse';

/**
 * 
 * @export
 * @interface OrgWebhookListPayload
 */
export interface OrgWebhookListPayload {
    /**
     * 
     * @type {Array<DiscordWebhookResponse>}
     * @memberof OrgWebhookListPayload
     */
    items: Array<DiscordWebhookResponse> | null;
}

/**
 * Check if a given object implements the OrgWebhookListPayload interface.
 */
export function instanceOfOrgWebhookListPayload(value: object): value is OrgWebhookListPayload {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function OrgWebhookListPayloadFromJSON(json: any): OrgWebhookListPayload {
    return OrgWebhookListPayloadFromJSONTyped(json, false);
}

export function OrgWebhookListPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgWebhookListPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'items': (json['items'] == null ? null : (json['items'] as Array<any>).map(DiscordWebhookResponseFromJSON)),
    };
}

export function OrgWebhookListPayloadToJSON(json: any): OrgWebhookListPayload {
    return OrgWebhookListPayloadToJSONTyped(json, false);
}

export function OrgWebhookListPayloadToJSONTyped(value?: OrgWebhookListPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': (value['items'] == null ? null : (value['items'] as Array<any>).map(DiscordWebhookResponseToJSON)),
    };
}

