/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface PageOrder
 */
export interface PageOrder {
    /**
     * 
     * @type {Array<Order>}
     * @memberof PageOrder
     */
    items: Array<Order> | null;
}

/**
 * Check if a given object implements the PageOrder interface.
 */
export function instanceOfPageOrder(value: object): value is PageOrder {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PageOrderFromJSON(json: any): PageOrder {
    return PageOrderFromJSONTyped(json, false);
}

export function PageOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'items': (json['items'] == null ? null : (json['items'] as Array<any>).map(OrderFromJSON)),
    };
}

export function PageOrderToJSON(json: any): PageOrder {
    return PageOrderToJSONTyped(json, false);
}

export function PageOrderToJSONTyped(value?: PageOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': (value['items'] == null ? null : (value['items'] as Array<any>).map(OrderToJSON)),
    };
}

