/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelShareGrant } from './ModelShareGrant';
import {
    ModelShareGrantFromJSON,
    ModelShareGrantFromJSONTyped,
    ModelShareGrantToJSON,
    ModelShareGrantToJSONTyped,
} from './ModelShareGrant';

/**
 * 
 * @export
 * @interface PageModelShareGrant
 */
export interface PageModelShareGrant {
    /**
     * 
     * @type {Array<ModelShareGrant>}
     * @memberof PageModelShareGrant
     */
    items: Array<ModelShareGrant> | null;
}

/**
 * Check if a given object implements the PageModelShareGrant interface.
 */
export function instanceOfPageModelShareGrant(value: object): value is PageModelShareGrant {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PageModelShareGrantFromJSON(json: any): PageModelShareGrant {
    return PageModelShareGrantFromJSONTyped(json, false);
}

export function PageModelShareGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageModelShareGrant {
    if (json == null) {
        return json;
    }
    return {
        
        'items': (json['items'] == null ? null : (json['items'] as Array<any>).map(ModelShareGrantFromJSON)),
    };
}

export function PageModelShareGrantToJSON(json: any): PageModelShareGrant {
    return PageModelShareGrantToJSONTyped(json, false);
}

export function PageModelShareGrantToJSONTyped(value?: PageModelShareGrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': (value['items'] == null ? null : (value['items'] as Array<any>).map(ModelShareGrantToJSON)),
    };
}

