/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineStepResponse
 */
export interface PipelineStepResponse {
    /**
     * 
     * @type {Date}
     * @memberof PipelineStepResponse
     */
    endedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PipelineStepResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineStepResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof PipelineStepResponse
     */
    startedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PipelineStepResponse
     */
    status: string;
}

/**
 * Check if a given object implements the PipelineStepResponse interface.
 */
export function instanceOfPipelineStepResponse(value: object): value is PipelineStepResponse {
    if (!('endedAt' in value) || value['endedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PipelineStepResponseFromJSON(json: any): PipelineStepResponse {
    return PipelineStepResponseFromJSONTyped(json, false);
}

export function PipelineStepResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineStepResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'endedAt': (json['endedAt'] == null ? null : new Date(json['endedAt'])),
        'id': json['id'],
        'name': json['name'],
        'startedAt': (json['startedAt'] == null ? null : new Date(json['startedAt'])),
        'status': json['status'],
    };
}

export function PipelineStepResponseToJSON(json: any): PipelineStepResponse {
    return PipelineStepResponseToJSONTyped(json, false);
}

export function PipelineStepResponseToJSONTyped(value?: PipelineStepResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endedAt': (value['endedAt'] == null ? null : (value['endedAt'] as any).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'startedAt': (value['startedAt'] == null ? null : (value['startedAt'] as any).toISOString()),
        'status': value['status'],
    };
}

