/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PoolDeclinedResult
 */
export interface PoolDeclinedResult {
    /**
     * 
     * @type {boolean}
     * @memberof PoolDeclinedResult
     */
    declined: boolean;
}

/**
 * Check if a given object implements the PoolDeclinedResult interface.
 */
export function instanceOfPoolDeclinedResult(value: object): value is PoolDeclinedResult {
    if (!('declined' in value) || value['declined'] === undefined) return false;
    return true;
}

export function PoolDeclinedResultFromJSON(json: any): PoolDeclinedResult {
    return PoolDeclinedResultFromJSONTyped(json, false);
}

export function PoolDeclinedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoolDeclinedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'declined': json['declined'],
    };
}

export function PoolDeclinedResultToJSON(json: any): PoolDeclinedResult {
    return PoolDeclinedResultToJSONTyped(json, false);
}

export function PoolDeclinedResultToJSONTyped(value?: PoolDeclinedResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'declined': value['declined'],
    };
}

