/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PoolRevokedResult
 */
export interface PoolRevokedResult {
    /**
     * 
     * @type {boolean}
     * @memberof PoolRevokedResult
     */
    revoked: boolean;
}

/**
 * Check if a given object implements the PoolRevokedResult interface.
 */
export function instanceOfPoolRevokedResult(value: object): value is PoolRevokedResult {
    if (!('revoked' in value) || value['revoked'] === undefined) return false;
    return true;
}

export function PoolRevokedResultFromJSON(json: any): PoolRevokedResult {
    return PoolRevokedResultFromJSONTyped(json, false);
}

export function PoolRevokedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoolRevokedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'revoked': json['revoked'],
    };
}

export function PoolRevokedResultToJSON(json: any): PoolRevokedResult {
    return PoolRevokedResultToJSONTyped(json, false);
}

export function PoolRevokedResultToJSONTyped(value?: PoolRevokedResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'revoked': value['revoked'],
    };
}

