/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PoolMemberRequestBody
 */
export interface PoolMemberRequestBody {
    /**
     * 
     * @type {string}
     * @memberof PoolMemberRequestBody
     */
    memberId: string;
}

/**
 * Check if a given object implements the PoolMemberRequestBody interface.
 */
export function instanceOfPoolMemberRequestBody(value: object): value is PoolMemberRequestBody {
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    return true;
}

export function PoolMemberRequestBodyFromJSON(json: any): PoolMemberRequestBody {
    return PoolMemberRequestBodyFromJSONTyped(json, false);
}

export function PoolMemberRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoolMemberRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['member_id'],
    };
}

export function PoolMemberRequestBodyToJSON(json: any): PoolMemberRequestBody {
    return PoolMemberRequestBodyToJSONTyped(json, false);
}

export function PoolMemberRequestBodyToJSONTyped(value?: PoolMemberRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member_id': value['memberId'],
    };
}

