/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostTargetCreateBody } from './PostTargetCreateBody';
import {
    PostTargetCreateBodyFromJSON,
    PostTargetCreateBodyFromJSONTyped,
    PostTargetCreateBodyToJSON,
    PostTargetCreateBodyToJSONTyped,
} from './PostTargetCreateBody';

/**
 * 
 * @export
 * @interface PostCreateBody
 */
export interface PostCreateBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof PostCreateBody
     */
    attachments?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof PostCreateBody
     */
    bodyText: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreateBody
     */
    modelId: string;
    /**
     * 
     * @type {string}
     * @memberof PostCreateBody
     */
    orgId: string;
    /**
     * 
     * @type {Date}
     * @memberof PostCreateBody
     */
    publishAt?: Date;
    /**
     * 
     * @type {Array<PostTargetCreateBody>}
     * @memberof PostCreateBody
     */
    targets?: Array<PostTargetCreateBody> | null;
}

/**
 * Check if a given object implements the PostCreateBody interface.
 */
export function instanceOfPostCreateBody(value: object): value is PostCreateBody {
    if (!('bodyText' in value) || value['bodyText'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    return true;
}

export function PostCreateBodyFromJSON(json: any): PostCreateBody {
    return PostCreateBodyFromJSONTyped(json, false);
}

export function PostCreateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCreateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'attachments': json['attachments'] == null ? undefined : json['attachments'],
        'bodyText': json['body_text'],
        'modelId': json['model_id'],
        'orgId': json['org_id'],
        'publishAt': json['publish_at'] == null ? undefined : (new Date(json['publish_at'])),
        'targets': json['targets'] == null ? undefined : ((json['targets'] as Array<any>).map(PostTargetCreateBodyFromJSON)),
    };
}

export function PostCreateBodyToJSON(json: any): PostCreateBody {
    return PostCreateBodyToJSONTyped(json, false);
}

export function PostCreateBodyToJSONTyped(value?: PostCreateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attachments': value['attachments'],
        'body_text': value['bodyText'],
        'model_id': value['modelId'],
        'org_id': value['orgId'],
        'publish_at': value['publishAt'] == null ? undefined : ((value['publishAt']).toISOString()),
        'targets': value['targets'] == null ? undefined : ((value['targets'] as Array<any>).map(PostTargetCreateBodyToJSON)),
    };
}

