/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterSettingsResult
 */
export interface RegisterSettingsResult {
    /**
     * 
     * @type {boolean}
     * @memberof RegisterSettingsResult
     */
    registrationCodesEnabled: boolean;
}

/**
 * Check if a given object implements the RegisterSettingsResult interface.
 */
export function instanceOfRegisterSettingsResult(value: object): value is RegisterSettingsResult {
    if (!('registrationCodesEnabled' in value) || value['registrationCodesEnabled'] === undefined) return false;
    return true;
}

export function RegisterSettingsResultFromJSON(json: any): RegisterSettingsResult {
    return RegisterSettingsResultFromJSONTyped(json, false);
}

export function RegisterSettingsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterSettingsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'registrationCodesEnabled': json['registration_codes_enabled'],
    };
}

export function RegisterSettingsResultToJSON(json: any): RegisterSettingsResult {
    return RegisterSettingsResultToJSONTyped(json, false);
}

export function RegisterSettingsResultToJSONTyped(value?: RegisterSettingsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'registration_codes_enabled': value['registrationCodesEnabled'],
    };
}

