/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevenueEvent
 */
export interface RevenueEvent {
    /**
     * 
     * @type {number}
     * @memberof RevenueEvent
     */
    amountCents: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueEvent
     */
    connectedAccountId: string;
    /**
     * 
     * @type {Date}
     * @memberof RevenueEvent
     */
    createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RevenueEvent
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueEvent
     */
    modelId: string;
    /**
     * 
     * @type {Date}
     * @memberof RevenueEvent
     */
    occurredAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RevenueEvent
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueEvent
     */
    remoteEventId: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueEvent
     */
    revenueType: string;
}

/**
 * Check if a given object implements the RevenueEvent interface.
 */
export function instanceOfRevenueEvent(value: object): value is RevenueEvent {
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('connectedAccountId' in value) || value['connectedAccountId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('remoteEventId' in value) || value['remoteEventId'] === undefined) return false;
    if (!('revenueType' in value) || value['revenueType'] === undefined) return false;
    return true;
}

export function RevenueEventFromJSON(json: any): RevenueEvent {
    return RevenueEventFromJSONTyped(json, false);
}

export function RevenueEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevenueEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'amountCents': json['amount_cents'],
        'connectedAccountId': json['connected_account_id'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'currency': json['currency'],
        'id': json['id'],
        'modelId': json['model_id'],
        'occurredAt': (new Date(json['occurred_at'])),
        'platform': json['platform'],
        'remoteEventId': json['remote_event_id'],
        'revenueType': json['revenue_type'],
    };
}

export function RevenueEventToJSON(json: any): RevenueEvent {
    return RevenueEventToJSONTyped(json, false);
}

export function RevenueEventToJSONTyped(value?: RevenueEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amountCents'],
        'connected_account_id': value['connectedAccountId'],
        'created_at': (value['createdAt'] == null ? null : (value['createdAt'] as any).toISOString()),
        'currency': value['currency'],
        'id': value['id'],
        'model_id': value['modelId'],
        'occurred_at': ((value['occurredAt']).toISOString()),
        'platform': value['platform'],
        'remote_event_id': value['remoteEventId'],
        'revenue_type': value['revenueType'],
    };
}

