/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleCatalogPlatform } from './ScheduleCatalogPlatform';
import {
    ScheduleCatalogPlatformFromJSON,
    ScheduleCatalogPlatformFromJSONTyped,
    ScheduleCatalogPlatformToJSON,
    ScheduleCatalogPlatformToJSONTyped,
} from './ScheduleCatalogPlatform';

/**
 * 
 * @export
 * @interface ScheduleCatalogResponse
 */
export interface ScheduleCatalogResponse {
    /**
     * 
     * @type {Array<ScheduleCatalogPlatform>}
     * @memberof ScheduleCatalogResponse
     */
    platforms: Array<ScheduleCatalogPlatform> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScheduleCatalogResponse
     */
    statuses: Array<string> | null;
}

/**
 * Check if a given object implements the ScheduleCatalogResponse interface.
 */
export function instanceOfScheduleCatalogResponse(value: object): value is ScheduleCatalogResponse {
    if (!('platforms' in value) || value['platforms'] === undefined) return false;
    if (!('statuses' in value) || value['statuses'] === undefined) return false;
    return true;
}

export function ScheduleCatalogResponseFromJSON(json: any): ScheduleCatalogResponse {
    return ScheduleCatalogResponseFromJSONTyped(json, false);
}

export function ScheduleCatalogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleCatalogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'platforms': (json['platforms'] == null ? null : (json['platforms'] as Array<any>).map(ScheduleCatalogPlatformFromJSON)),
        'statuses': json['statuses'] == null ? null : json['statuses'],
    };
}

export function ScheduleCatalogResponseToJSON(json: any): ScheduleCatalogResponse {
    return ScheduleCatalogResponseToJSONTyped(json, false);
}

export function ScheduleCatalogResponseToJSONTyped(value?: ScheduleCatalogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platforms': (value['platforms'] == null ? null : (value['platforms'] as Array<any>).map(ScheduleCatalogPlatformToJSON)),
        'statuses': value['statuses'],
    };
}

