/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageTrendPoint
 */
export interface StorageTrendPoint {
    /**
     * 
     * @type {number}
     * @memberof StorageTrendPoint
     */
    bytesUsed: number;
    /**
     * 
     * @type {string}
     * @memberof StorageTrendPoint
     */
    date: string;
}

/**
 * Check if a given object implements the StorageTrendPoint interface.
 */
export function instanceOfStorageTrendPoint(value: object): value is StorageTrendPoint {
    if (!('bytesUsed' in value) || value['bytesUsed'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function StorageTrendPointFromJSON(json: any): StorageTrendPoint {
    return StorageTrendPointFromJSONTyped(json, false);
}

export function StorageTrendPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageTrendPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'bytesUsed': json['bytes_used'],
        'date': json['date'],
    };
}

export function StorageTrendPointToJSON(json: any): StorageTrendPoint {
    return StorageTrendPointToJSONTyped(json, false);
}

export function StorageTrendPointToJSONTyped(value?: StorageTrendPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bytes_used': value['bytesUsed'],
        'date': value['date'],
    };
}

