/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { CaptionTemplateDeletionRes } from './CaptionTemplateDeletionRes';
import {
    CaptionTemplateDeletionResFromJSON,
    CaptionTemplateDeletionResFromJSONTyped,
    CaptionTemplateDeletionResToJSON,
    CaptionTemplateDeletionResToJSONTyped,
} from './CaptionTemplateDeletionRes';

/**
 * 
 * @export
 * @interface SuccessCaptionTemplateDeletionRes
 */
export interface SuccessCaptionTemplateDeletionRes {
    /**
     * 
     * @type {CaptionTemplateDeletionRes}
     * @memberof SuccessCaptionTemplateDeletionRes
     */
    data: CaptionTemplateDeletionRes;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessCaptionTemplateDeletionRes
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessCaptionTemplateDeletionRes
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessCaptionTemplateDeletionRes interface.
 */
export function instanceOfSuccessCaptionTemplateDeletionRes(value: object): value is SuccessCaptionTemplateDeletionRes {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessCaptionTemplateDeletionResFromJSON(json: any): SuccessCaptionTemplateDeletionRes {
    return SuccessCaptionTemplateDeletionResFromJSONTyped(json, false);
}

export function SuccessCaptionTemplateDeletionResFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCaptionTemplateDeletionRes {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CaptionTemplateDeletionResFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessCaptionTemplateDeletionResToJSON(json: any): SuccessCaptionTemplateDeletionRes {
    return SuccessCaptionTemplateDeletionResToJSONTyped(json, false);
}

export function SuccessCaptionTemplateDeletionResToJSONTyped(value?: SuccessCaptionTemplateDeletionRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CaptionTemplateDeletionResToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

