/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BuiltInTagsReadPayload } from './BuiltInTagsReadPayload';
import {
    BuiltInTagsReadPayloadFromJSON,
    BuiltInTagsReadPayloadFromJSONTyped,
    BuiltInTagsReadPayloadToJSON,
    BuiltInTagsReadPayloadToJSONTyped,
} from './BuiltInTagsReadPayload';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';

/**
 * 
 * @export
 * @interface SuccessBuiltInTagsReadPayload
 */
export interface SuccessBuiltInTagsReadPayload {
    /**
     * 
     * @type {BuiltInTagsReadPayload}
     * @memberof SuccessBuiltInTagsReadPayload
     */
    data: BuiltInTagsReadPayload;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessBuiltInTagsReadPayload
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessBuiltInTagsReadPayload
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessBuiltInTagsReadPayload interface.
 */
export function instanceOfSuccessBuiltInTagsReadPayload(value: object): value is SuccessBuiltInTagsReadPayload {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessBuiltInTagsReadPayloadFromJSON(json: any): SuccessBuiltInTagsReadPayload {
    return SuccessBuiltInTagsReadPayloadFromJSONTyped(json, false);
}

export function SuccessBuiltInTagsReadPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessBuiltInTagsReadPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BuiltInTagsReadPayloadFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessBuiltInTagsReadPayloadToJSON(json: any): SuccessBuiltInTagsReadPayload {
    return SuccessBuiltInTagsReadPayloadToJSONTyped(json, false);
}

export function SuccessBuiltInTagsReadPayloadToJSONTyped(value?: SuccessBuiltInTagsReadPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BuiltInTagsReadPayloadToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

