/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { CharacterPromptSchemaResponse } from './CharacterPromptSchemaResponse';
import {
    CharacterPromptSchemaResponseFromJSON,
    CharacterPromptSchemaResponseFromJSONTyped,
    CharacterPromptSchemaResponseToJSON,
    CharacterPromptSchemaResponseToJSONTyped,
} from './CharacterPromptSchemaResponse';

/**
 * 
 * @export
 * @interface SuccessCharacterPromptSchemaResponse
 */
export interface SuccessCharacterPromptSchemaResponse {
    /**
     * 
     * @type {CharacterPromptSchemaResponse}
     * @memberof SuccessCharacterPromptSchemaResponse
     */
    data: CharacterPromptSchemaResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessCharacterPromptSchemaResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessCharacterPromptSchemaResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessCharacterPromptSchemaResponse interface.
 */
export function instanceOfSuccessCharacterPromptSchemaResponse(value: object): value is SuccessCharacterPromptSchemaResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessCharacterPromptSchemaResponseFromJSON(json: any): SuccessCharacterPromptSchemaResponse {
    return SuccessCharacterPromptSchemaResponseFromJSONTyped(json, false);
}

export function SuccessCharacterPromptSchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCharacterPromptSchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CharacterPromptSchemaResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessCharacterPromptSchemaResponseToJSON(json: any): SuccessCharacterPromptSchemaResponse {
    return SuccessCharacterPromptSchemaResponseToJSONTyped(json, false);
}

export function SuccessCharacterPromptSchemaResponseToJSONTyped(value?: SuccessCharacterPromptSchemaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CharacterPromptSchemaResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

