/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { ScheduleDeletionRes } from './ScheduleDeletionRes';
import {
    ScheduleDeletionResFromJSON,
    ScheduleDeletionResFromJSONTyped,
    ScheduleDeletionResToJSON,
    ScheduleDeletionResToJSONTyped,
} from './ScheduleDeletionRes';

/**
 * 
 * @export
 * @interface SuccessScheduleDeletionRes
 */
export interface SuccessScheduleDeletionRes {
    /**
     * 
     * @type {ScheduleDeletionRes}
     * @memberof SuccessScheduleDeletionRes
     */
    data: ScheduleDeletionRes;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessScheduleDeletionRes
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessScheduleDeletionRes
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessScheduleDeletionRes interface.
 */
export function instanceOfSuccessScheduleDeletionRes(value: object): value is SuccessScheduleDeletionRes {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessScheduleDeletionResFromJSON(json: any): SuccessScheduleDeletionRes {
    return SuccessScheduleDeletionResFromJSONTyped(json, false);
}

export function SuccessScheduleDeletionResFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessScheduleDeletionRes {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ScheduleDeletionResFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessScheduleDeletionResToJSON(json: any): SuccessScheduleDeletionRes {
    return SuccessScheduleDeletionResToJSONTyped(json, false);
}

export function SuccessScheduleDeletionResToJSONTyped(value?: SuccessScheduleDeletionRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ScheduleDeletionResToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

