/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { UserCaptionTemplatesReadPayload } from './UserCaptionTemplatesReadPayload';
import {
    UserCaptionTemplatesReadPayloadFromJSON,
    UserCaptionTemplatesReadPayloadFromJSONTyped,
    UserCaptionTemplatesReadPayloadToJSON,
    UserCaptionTemplatesReadPayloadToJSONTyped,
} from './UserCaptionTemplatesReadPayload';

/**
 * 
 * @export
 * @interface SuccessUserCaptionTemplatesReadPayload
 */
export interface SuccessUserCaptionTemplatesReadPayload {
    /**
     * 
     * @type {UserCaptionTemplatesReadPayload}
     * @memberof SuccessUserCaptionTemplatesReadPayload
     */
    data: UserCaptionTemplatesReadPayload;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessUserCaptionTemplatesReadPayload
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessUserCaptionTemplatesReadPayload
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessUserCaptionTemplatesReadPayload interface.
 */
export function instanceOfSuccessUserCaptionTemplatesReadPayload(value: object): value is SuccessUserCaptionTemplatesReadPayload {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessUserCaptionTemplatesReadPayloadFromJSON(json: any): SuccessUserCaptionTemplatesReadPayload {
    return SuccessUserCaptionTemplatesReadPayloadFromJSONTyped(json, false);
}

export function SuccessUserCaptionTemplatesReadPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessUserCaptionTemplatesReadPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'data': UserCaptionTemplatesReadPayloadFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessUserCaptionTemplatesReadPayloadToJSON(json: any): SuccessUserCaptionTemplatesReadPayload {
    return SuccessUserCaptionTemplatesReadPayloadToJSONTyped(json, false);
}

export function SuccessUserCaptionTemplatesReadPayloadToJSONTyped(value?: SuccessUserCaptionTemplatesReadPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': UserCaptionTemplatesReadPayloadToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

