/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { AssetDeletionRes } from './AssetDeletionRes';
import {
    AssetDeletionResFromJSON,
    AssetDeletionResFromJSONTyped,
    AssetDeletionResToJSON,
    AssetDeletionResToJSONTyped,
} from './AssetDeletionRes';

/**
 * 
 * @export
 * @interface SuccessAssetDeletionRes
 */
export interface SuccessAssetDeletionRes {
    /**
     * 
     * @type {AssetDeletionRes}
     * @memberof SuccessAssetDeletionRes
     */
    data: AssetDeletionRes;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessAssetDeletionRes
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessAssetDeletionRes
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessAssetDeletionRes interface.
 */
export function instanceOfSuccessAssetDeletionRes(value: object): value is SuccessAssetDeletionRes {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessAssetDeletionResFromJSON(json: any): SuccessAssetDeletionRes {
    return SuccessAssetDeletionResFromJSONTyped(json, false);
}

export function SuccessAssetDeletionResFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessAssetDeletionRes {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AssetDeletionResFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessAssetDeletionResToJSON(json: any): SuccessAssetDeletionRes {
    return SuccessAssetDeletionResToJSONTyped(json, false);
}

export function SuccessAssetDeletionResToJSONTyped(value?: SuccessAssetDeletionRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AssetDeletionResToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

