/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { PageAlbumResponse } from './PageAlbumResponse';
import {
    PageAlbumResponseFromJSON,
    PageAlbumResponseFromJSONTyped,
    PageAlbumResponseToJSON,
    PageAlbumResponseToJSONTyped,
} from './PageAlbumResponse';

/**
 * 
 * @export
 * @interface SuccessPageAlbumResponse
 */
export interface SuccessPageAlbumResponse {
    /**
     * 
     * @type {PageAlbumResponse}
     * @memberof SuccessPageAlbumResponse
     */
    data: PageAlbumResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessPageAlbumResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPageAlbumResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessPageAlbumResponse interface.
 */
export function instanceOfSuccessPageAlbumResponse(value: object): value is SuccessPageAlbumResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessPageAlbumResponseFromJSON(json: any): SuccessPageAlbumResponse {
    return SuccessPageAlbumResponseFromJSONTyped(json, false);
}

export function SuccessPageAlbumResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPageAlbumResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PageAlbumResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessPageAlbumResponseToJSON(json: any): SuccessPageAlbumResponse {
    return SuccessPageAlbumResponseToJSONTyped(json, false);
}

export function SuccessPageAlbumResponseToJSONTyped(value?: SuccessPageAlbumResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PageAlbumResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

