/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { ThreadsConnectedAccount } from './ThreadsConnectedAccount';
import {
    ThreadsConnectedAccountFromJSON,
    ThreadsConnectedAccountFromJSONTyped,
    ThreadsConnectedAccountToJSON,
    ThreadsConnectedAccountToJSONTyped,
} from './ThreadsConnectedAccount';

/**
 * 
 * @export
 * @interface SuccessThreadsConnectedAccount
 */
export interface SuccessThreadsConnectedAccount {
    /**
     * 
     * @type {ThreadsConnectedAccount}
     * @memberof SuccessThreadsConnectedAccount
     */
    data: ThreadsConnectedAccount;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessThreadsConnectedAccount
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessThreadsConnectedAccount
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessThreadsConnectedAccount interface.
 */
export function instanceOfSuccessThreadsConnectedAccount(value: object): value is SuccessThreadsConnectedAccount {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessThreadsConnectedAccountFromJSON(json: any): SuccessThreadsConnectedAccount {
    return SuccessThreadsConnectedAccountFromJSONTyped(json, false);
}

export function SuccessThreadsConnectedAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessThreadsConnectedAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ThreadsConnectedAccountFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessThreadsConnectedAccountToJSON(json: any): SuccessThreadsConnectedAccount {
    return SuccessThreadsConnectedAccountToJSONTyped(json, false);
}

export function SuccessThreadsConnectedAccountToJSONTyped(value?: SuccessThreadsConnectedAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ThreadsConnectedAccountToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

