/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
    SubscriptionToJSONTyped,
} from './Subscription';

/**
 * 
 * @export
 * @interface SuccessSubscription
 */
export interface SuccessSubscription {
    /**
     * 
     * @type {Subscription}
     * @memberof SuccessSubscription
     */
    data: Subscription;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessSubscription
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessSubscription
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessSubscription interface.
 */
export function instanceOfSuccessSubscription(value: object): value is SuccessSubscription {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessSubscriptionFromJSON(json: any): SuccessSubscription {
    return SuccessSubscriptionFromJSONTyped(json, false);
}

export function SuccessSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SubscriptionFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessSubscriptionToJSON(json: any): SuccessSubscription {
    return SuccessSubscriptionToJSONTyped(json, false);
}

export function SuccessSubscriptionToJSONTyped(value?: SuccessSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SubscriptionToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

