/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { AuthMeResult } from './AuthMeResult';
import {
    AuthMeResultFromJSON,
    AuthMeResultFromJSONTyped,
    AuthMeResultToJSON,
    AuthMeResultToJSONTyped,
} from './AuthMeResult';

/**
 * 
 * @export
 * @interface SuccessAuthMeResult
 */
export interface SuccessAuthMeResult {
    /**
     * 
     * @type {AuthMeResult}
     * @memberof SuccessAuthMeResult
     */
    data: AuthMeResult;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessAuthMeResult
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessAuthMeResult
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessAuthMeResult interface.
 */
export function instanceOfSuccessAuthMeResult(value: object): value is SuccessAuthMeResult {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessAuthMeResultFromJSON(json: any): SuccessAuthMeResult {
    return SuccessAuthMeResultFromJSONTyped(json, false);
}

export function SuccessAuthMeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessAuthMeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AuthMeResultFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessAuthMeResultToJSON(json: any): SuccessAuthMeResult {
    return SuccessAuthMeResultToJSONTyped(json, false);
}

export function SuccessAuthMeResultToJSONTyped(value?: SuccessAuthMeResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AuthMeResultToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

