/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PoolDeclinedResult } from './PoolDeclinedResult';
import {
    PoolDeclinedResultFromJSON,
    PoolDeclinedResultFromJSONTyped,
    PoolDeclinedResultToJSON,
    PoolDeclinedResultToJSONTyped,
} from './PoolDeclinedResult';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';

/**
 * 
 * @export
 * @interface SuccessPoolDeclinedResult
 */
export interface SuccessPoolDeclinedResult {
    /**
     * 
     * @type {PoolDeclinedResult}
     * @memberof SuccessPoolDeclinedResult
     */
    data: PoolDeclinedResult;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessPoolDeclinedResult
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPoolDeclinedResult
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessPoolDeclinedResult interface.
 */
export function instanceOfSuccessPoolDeclinedResult(value: object): value is SuccessPoolDeclinedResult {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessPoolDeclinedResultFromJSON(json: any): SuccessPoolDeclinedResult {
    return SuccessPoolDeclinedResultFromJSONTyped(json, false);
}

export function SuccessPoolDeclinedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPoolDeclinedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PoolDeclinedResultFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessPoolDeclinedResultToJSON(json: any): SuccessPoolDeclinedResult {
    return SuccessPoolDeclinedResultToJSONTyped(json, false);
}

export function SuccessPoolDeclinedResultToJSONTyped(value?: SuccessPoolDeclinedResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PoolDeclinedResultToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

