/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { RepoProbeResult } from './RepoProbeResult';
import {
    RepoProbeResultFromJSON,
    RepoProbeResultFromJSONTyped,
    RepoProbeResultToJSON,
    RepoProbeResultToJSONTyped,
} from './RepoProbeResult';

/**
 * 
 * @export
 * @interface SuccessRepoProbeResult
 */
export interface SuccessRepoProbeResult {
    /**
     * 
     * @type {RepoProbeResult}
     * @memberof SuccessRepoProbeResult
     */
    data: RepoProbeResult;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessRepoProbeResult
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessRepoProbeResult
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessRepoProbeResult interface.
 */
export function instanceOfSuccessRepoProbeResult(value: object): value is SuccessRepoProbeResult {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessRepoProbeResultFromJSON(json: any): SuccessRepoProbeResult {
    return SuccessRepoProbeResultFromJSONTyped(json, false);
}

export function SuccessRepoProbeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessRepoProbeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'data': RepoProbeResultFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessRepoProbeResultToJSON(json: any): SuccessRepoProbeResult {
    return SuccessRepoProbeResultToJSONTyped(json, false);
}

export function SuccessRepoProbeResultToJSONTyped(value?: SuccessRepoProbeResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RepoProbeResultToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

