/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { AlbumSharesPayload } from './AlbumSharesPayload';
import {
    AlbumSharesPayloadFromJSON,
    AlbumSharesPayloadFromJSONTyped,
    AlbumSharesPayloadToJSON,
    AlbumSharesPayloadToJSONTyped,
} from './AlbumSharesPayload';

/**
 * 
 * @export
 * @interface SuccessAlbumSharesPayload
 */
export interface SuccessAlbumSharesPayload {
    /**
     * 
     * @type {AlbumSharesPayload}
     * @memberof SuccessAlbumSharesPayload
     */
    data: AlbumSharesPayload;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessAlbumSharesPayload
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessAlbumSharesPayload
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessAlbumSharesPayload interface.
 */
export function instanceOfSuccessAlbumSharesPayload(value: object): value is SuccessAlbumSharesPayload {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessAlbumSharesPayloadFromJSON(json: any): SuccessAlbumSharesPayload {
    return SuccessAlbumSharesPayloadFromJSONTyped(json, false);
}

export function SuccessAlbumSharesPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessAlbumSharesPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AlbumSharesPayloadFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessAlbumSharesPayloadToJSON(json: any): SuccessAlbumSharesPayload {
    return SuccessAlbumSharesPayloadToJSONTyped(json, false);
}

export function SuccessAlbumSharesPayloadToJSONTyped(value?: SuccessAlbumSharesPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AlbumSharesPayloadToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

