/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { PageOfSessions } from './PageOfSessions';
import {
    PageOfSessionsFromJSON,
    PageOfSessionsFromJSONTyped,
    PageOfSessionsToJSON,
    PageOfSessionsToJSONTyped,
} from './PageOfSessions';

/**
 * 
 * @export
 * @interface SuccessPageOfSessions
 */
export interface SuccessPageOfSessions {
    /**
     * 
     * @type {PageOfSessions}
     * @memberof SuccessPageOfSessions
     */
    data: PageOfSessions;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessPageOfSessions
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPageOfSessions
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessPageOfSessions interface.
 */
export function instanceOfSuccessPageOfSessions(value: object): value is SuccessPageOfSessions {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessPageOfSessionsFromJSON(json: any): SuccessPageOfSessions {
    return SuccessPageOfSessionsFromJSONTyped(json, false);
}

export function SuccessPageOfSessionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPageOfSessions {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PageOfSessionsFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessPageOfSessionsToJSON(json: any): SuccessPageOfSessions {
    return SuccessPageOfSessionsToJSONTyped(json, false);
}

export function SuccessPageOfSessionsToJSONTyped(value?: SuccessPageOfSessions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PageOfSessionsToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

