/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { WorkflowDetailResponse } from './WorkflowDetailResponse';
import {
    WorkflowDetailResponseFromJSON,
    WorkflowDetailResponseFromJSONTyped,
    WorkflowDetailResponseToJSON,
    WorkflowDetailResponseToJSONTyped,
} from './WorkflowDetailResponse';

/**
 * 
 * @export
 * @interface SuccessWorkflowDetailResponse
 */
export interface SuccessWorkflowDetailResponse {
    /**
     * 
     * @type {WorkflowDetailResponse}
     * @memberof SuccessWorkflowDetailResponse
     */
    data: WorkflowDetailResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessWorkflowDetailResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessWorkflowDetailResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessWorkflowDetailResponse interface.
 */
export function instanceOfSuccessWorkflowDetailResponse(value: object): value is SuccessWorkflowDetailResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessWorkflowDetailResponseFromJSON(json: any): SuccessWorkflowDetailResponse {
    return SuccessWorkflowDetailResponseFromJSONTyped(json, false);
}

export function SuccessWorkflowDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessWorkflowDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': WorkflowDetailResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessWorkflowDetailResponseToJSON(json: any): SuccessWorkflowDetailResponse {
    return SuccessWorkflowDetailResponseToJSONTyped(json, false);
}

export function SuccessWorkflowDetailResponseToJSONTyped(value?: SuccessWorkflowDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': WorkflowDetailResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

