/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { CollectionItemDetail } from './CollectionItemDetail';
import {
    CollectionItemDetailFromJSON,
    CollectionItemDetailFromJSONTyped,
    CollectionItemDetailToJSON,
    CollectionItemDetailToJSONTyped,
} from './CollectionItemDetail';

/**
 * 
 * @export
 * @interface SuccessCollectionItemDetail
 */
export interface SuccessCollectionItemDetail {
    /**
     * 
     * @type {CollectionItemDetail}
     * @memberof SuccessCollectionItemDetail
     */
    data: CollectionItemDetail;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessCollectionItemDetail
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessCollectionItemDetail
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessCollectionItemDetail interface.
 */
export function instanceOfSuccessCollectionItemDetail(value: object): value is SuccessCollectionItemDetail {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessCollectionItemDetailFromJSON(json: any): SuccessCollectionItemDetail {
    return SuccessCollectionItemDetailFromJSONTyped(json, false);
}

export function SuccessCollectionItemDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCollectionItemDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CollectionItemDetailFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessCollectionItemDetailToJSON(json: any): SuccessCollectionItemDetail {
    return SuccessCollectionItemDetailToJSONTyped(json, false);
}

export function SuccessCollectionItemDetailToJSONTyped(value?: SuccessCollectionItemDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CollectionItemDetailToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

