/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { ModelJobResponse } from './ModelJobResponse';
import {
    ModelJobResponseFromJSON,
    ModelJobResponseFromJSONTyped,
    ModelJobResponseToJSON,
    ModelJobResponseToJSONTyped,
} from './ModelJobResponse';

/**
 * 
 * @export
 * @interface SuccessModelJobResponse
 */
export interface SuccessModelJobResponse {
    /**
     * 
     * @type {ModelJobResponse}
     * @memberof SuccessModelJobResponse
     */
    data: ModelJobResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessModelJobResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessModelJobResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessModelJobResponse interface.
 */
export function instanceOfSuccessModelJobResponse(value: object): value is SuccessModelJobResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessModelJobResponseFromJSON(json: any): SuccessModelJobResponse {
    return SuccessModelJobResponseFromJSONTyped(json, false);
}

export function SuccessModelJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessModelJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ModelJobResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessModelJobResponseToJSON(json: any): SuccessModelJobResponse {
    return SuccessModelJobResponseToJSONTyped(json, false);
}

export function SuccessModelJobResponseToJSONTyped(value?: SuccessModelJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ModelJobResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

