/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { CharacterCreationEnqueueResponse } from './CharacterCreationEnqueueResponse';
import {
    CharacterCreationEnqueueResponseFromJSON,
    CharacterCreationEnqueueResponseFromJSONTyped,
    CharacterCreationEnqueueResponseToJSON,
    CharacterCreationEnqueueResponseToJSONTyped,
} from './CharacterCreationEnqueueResponse';

/**
 * 
 * @export
 * @interface SuccessCharacterCreationEnqueueResponse
 */
export interface SuccessCharacterCreationEnqueueResponse {
    /**
     * 
     * @type {CharacterCreationEnqueueResponse}
     * @memberof SuccessCharacterCreationEnqueueResponse
     */
    data: CharacterCreationEnqueueResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessCharacterCreationEnqueueResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessCharacterCreationEnqueueResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessCharacterCreationEnqueueResponse interface.
 */
export function instanceOfSuccessCharacterCreationEnqueueResponse(value: object): value is SuccessCharacterCreationEnqueueResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessCharacterCreationEnqueueResponseFromJSON(json: any): SuccessCharacterCreationEnqueueResponse {
    return SuccessCharacterCreationEnqueueResponseFromJSONTyped(json, false);
}

export function SuccessCharacterCreationEnqueueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCharacterCreationEnqueueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CharacterCreationEnqueueResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessCharacterCreationEnqueueResponseToJSON(json: any): SuccessCharacterCreationEnqueueResponse {
    return SuccessCharacterCreationEnqueueResponseToJSONTyped(json, false);
}

export function SuccessCharacterCreationEnqueueResponseToJSONTyped(value?: SuccessCharacterCreationEnqueueResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CharacterCreationEnqueueResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

