/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { CivitaiKeyItem } from './CivitaiKeyItem';
import {
    CivitaiKeyItemFromJSON,
    CivitaiKeyItemFromJSONTyped,
    CivitaiKeyItemToJSON,
    CivitaiKeyItemToJSONTyped,
} from './CivitaiKeyItem';

/**
 * 
 * @export
 * @interface SuccessCivitaiKeyItem
 */
export interface SuccessCivitaiKeyItem {
    /**
     * 
     * @type {CivitaiKeyItem}
     * @memberof SuccessCivitaiKeyItem
     */
    data: CivitaiKeyItem;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessCivitaiKeyItem
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessCivitaiKeyItem
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessCivitaiKeyItem interface.
 */
export function instanceOfSuccessCivitaiKeyItem(value: object): value is SuccessCivitaiKeyItem {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessCivitaiKeyItemFromJSON(json: any): SuccessCivitaiKeyItem {
    return SuccessCivitaiKeyItemFromJSONTyped(json, false);
}

export function SuccessCivitaiKeyItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessCivitaiKeyItem {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CivitaiKeyItemFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessCivitaiKeyItemToJSON(json: any): SuccessCivitaiKeyItem {
    return SuccessCivitaiKeyItemToJSONTyped(json, false);
}

export function SuccessCivitaiKeyItemToJSONTyped(value?: SuccessCivitaiKeyItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CivitaiKeyItemToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

