/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowToolsResponse } from './WorkflowToolsResponse';
import {
    WorkflowToolsResponseFromJSON,
    WorkflowToolsResponseFromJSONTyped,
    WorkflowToolsResponseToJSON,
    WorkflowToolsResponseToJSONTyped,
} from './WorkflowToolsResponse';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';

/**
 * 
 * @export
 * @interface SuccessWorkflowToolsResponse
 */
export interface SuccessWorkflowToolsResponse {
    /**
     * 
     * @type {WorkflowToolsResponse}
     * @memberof SuccessWorkflowToolsResponse
     */
    data: WorkflowToolsResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessWorkflowToolsResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessWorkflowToolsResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessWorkflowToolsResponse interface.
 */
export function instanceOfSuccessWorkflowToolsResponse(value: object): value is SuccessWorkflowToolsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessWorkflowToolsResponseFromJSON(json: any): SuccessWorkflowToolsResponse {
    return SuccessWorkflowToolsResponseFromJSONTyped(json, false);
}

export function SuccessWorkflowToolsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessWorkflowToolsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': WorkflowToolsResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessWorkflowToolsResponseToJSON(json: any): SuccessWorkflowToolsResponse {
    return SuccessWorkflowToolsResponseToJSONTyped(json, false);
}

export function SuccessWorkflowToolsResponseToJSONTyped(value?: SuccessWorkflowToolsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': WorkflowToolsResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

