/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { PageNotificationResponse } from './PageNotificationResponse';
import {
    PageNotificationResponseFromJSON,
    PageNotificationResponseFromJSONTyped,
    PageNotificationResponseToJSON,
    PageNotificationResponseToJSONTyped,
} from './PageNotificationResponse';

/**
 * 
 * @export
 * @interface SuccessPageNotificationResponse
 */
export interface SuccessPageNotificationResponse {
    /**
     * 
     * @type {PageNotificationResponse}
     * @memberof SuccessPageNotificationResponse
     */
    data: PageNotificationResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessPageNotificationResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPageNotificationResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessPageNotificationResponse interface.
 */
export function instanceOfSuccessPageNotificationResponse(value: object): value is SuccessPageNotificationResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessPageNotificationResponseFromJSON(json: any): SuccessPageNotificationResponse {
    return SuccessPageNotificationResponseFromJSONTyped(json, false);
}

export function SuccessPageNotificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPageNotificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PageNotificationResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessPageNotificationResponseToJSON(json: any): SuccessPageNotificationResponse {
    return SuccessPageNotificationResponseToJSONTyped(json, false);
}

export function SuccessPageNotificationResponseToJSONTyped(value?: SuccessPageNotificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PageNotificationResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

