/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { ModePopularityResponse } from './ModePopularityResponse';
import {
    ModePopularityResponseFromJSON,
    ModePopularityResponseFromJSONTyped,
    ModePopularityResponseToJSON,
    ModePopularityResponseToJSONTyped,
} from './ModePopularityResponse';

/**
 * 
 * @export
 * @interface SuccessModePopularityResponse
 */
export interface SuccessModePopularityResponse {
    /**
     * 
     * @type {ModePopularityResponse}
     * @memberof SuccessModePopularityResponse
     */
    data: ModePopularityResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessModePopularityResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessModePopularityResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessModePopularityResponse interface.
 */
export function instanceOfSuccessModePopularityResponse(value: object): value is SuccessModePopularityResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessModePopularityResponseFromJSON(json: any): SuccessModePopularityResponse {
    return SuccessModePopularityResponseFromJSONTyped(json, false);
}

export function SuccessModePopularityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessModePopularityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ModePopularityResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessModePopularityResponseToJSON(json: any): SuccessModePopularityResponse {
    return SuccessModePopularityResponseToJSONTyped(json, false);
}

export function SuccessModePopularityResponseToJSONTyped(value?: SuccessModePopularityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ModePopularityResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

