/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { PageFrontendResponse } from './PageFrontendResponse';
import {
    PageFrontendResponseFromJSON,
    PageFrontendResponseFromJSONTyped,
    PageFrontendResponseToJSON,
    PageFrontendResponseToJSONTyped,
} from './PageFrontendResponse';

/**
 * 
 * @export
 * @interface SuccessPageFrontendResponse
 */
export interface SuccessPageFrontendResponse {
    /**
     * 
     * @type {PageFrontendResponse}
     * @memberof SuccessPageFrontendResponse
     */
    data: PageFrontendResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessPageFrontendResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPageFrontendResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessPageFrontendResponse interface.
 */
export function instanceOfSuccessPageFrontendResponse(value: object): value is SuccessPageFrontendResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessPageFrontendResponseFromJSON(json: any): SuccessPageFrontendResponse {
    return SuccessPageFrontendResponseFromJSONTyped(json, false);
}

export function SuccessPageFrontendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPageFrontendResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PageFrontendResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessPageFrontendResponseToJSON(json: any): SuccessPageFrontendResponse {
    return SuccessPageFrontendResponseToJSONTyped(json, false);
}

export function SuccessPageFrontendResponseToJSONTyped(value?: SuccessPageFrontendResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PageFrontendResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

