/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface SuccessListProduct
 */
export interface SuccessListProduct {
    /**
     * 
     * @type {Array<Product>}
     * @memberof SuccessListProduct
     */
    data: Array<Product> | null;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessListProduct
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessListProduct
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessListProduct interface.
 */
export function instanceOfSuccessListProduct(value: object): value is SuccessListProduct {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessListProductFromJSON(json: any): SuccessListProduct {
    return SuccessListProductFromJSONTyped(json, false);
}

export function SuccessListProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessListProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(ProductFromJSON)),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessListProductToJSON(json: any): SuccessListProduct {
    return SuccessListProductToJSONTyped(json, false);
}

export function SuccessListProductToJSONTyped(value?: SuccessListProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(ProductToJSON)),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

