/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { EnumsResponse } from './EnumsResponse';
import {
    EnumsResponseFromJSON,
    EnumsResponseFromJSONTyped,
    EnumsResponseToJSON,
    EnumsResponseToJSONTyped,
} from './EnumsResponse';

/**
 * 
 * @export
 * @interface SuccessEnumsResponse
 */
export interface SuccessEnumsResponse {
    /**
     * 
     * @type {EnumsResponse}
     * @memberof SuccessEnumsResponse
     */
    data: EnumsResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessEnumsResponse
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessEnumsResponse
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessEnumsResponse interface.
 */
export function instanceOfSuccessEnumsResponse(value: object): value is SuccessEnumsResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessEnumsResponseFromJSON(json: any): SuccessEnumsResponse {
    return SuccessEnumsResponseFromJSONTyped(json, false);
}

export function SuccessEnumsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessEnumsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': EnumsResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessEnumsResponseToJSON(json: any): SuccessEnumsResponse {
    return SuccessEnumsResponseToJSONTyped(json, false);
}

export function SuccessEnumsResponseToJSONTyped(value?: SuccessEnumsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': EnumsResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

