/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { PageModelShareGrant } from './PageModelShareGrant';
import {
    PageModelShareGrantFromJSON,
    PageModelShareGrantFromJSONTyped,
    PageModelShareGrantToJSON,
    PageModelShareGrantToJSONTyped,
} from './PageModelShareGrant';

/**
 * 
 * @export
 * @interface SuccessPageModelShareGrant
 */
export interface SuccessPageModelShareGrant {
    /**
     * 
     * @type {PageModelShareGrant}
     * @memberof SuccessPageModelShareGrant
     */
    data: PageModelShareGrant;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessPageModelShareGrant
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessPageModelShareGrant
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessPageModelShareGrant interface.
 */
export function instanceOfSuccessPageModelShareGrant(value: object): value is SuccessPageModelShareGrant {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessPageModelShareGrantFromJSON(json: any): SuccessPageModelShareGrant {
    return SuccessPageModelShareGrantFromJSONTyped(json, false);
}

export function SuccessPageModelShareGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessPageModelShareGrant {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PageModelShareGrantFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessPageModelShareGrantToJSON(json: any): SuccessPageModelShareGrant {
    return SuccessPageModelShareGrantToJSONTyped(json, false);
}

export function SuccessPageModelShareGrantToJSONTyped(value?: SuccessPageModelShareGrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PageModelShareGrantToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

