/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvatarProfilesPayload } from './AvatarProfilesPayload';
import {
    AvatarProfilesPayloadFromJSON,
    AvatarProfilesPayloadFromJSONTyped,
    AvatarProfilesPayloadToJSON,
    AvatarProfilesPayloadToJSONTyped,
} from './AvatarProfilesPayload';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';

/**
 * 
 * @export
 * @interface SuccessAvatarProfilesPayload
 */
export interface SuccessAvatarProfilesPayload {
    /**
     * 
     * @type {AvatarProfilesPayload}
     * @memberof SuccessAvatarProfilesPayload
     */
    data: AvatarProfilesPayload;
    /**
     * 
     * @type {Meta}
     * @memberof SuccessAvatarProfilesPayload
     */
    meta: Meta;
    /**
     * 
     * @type {boolean}
     * @memberof SuccessAvatarProfilesPayload
     */
    ok: boolean;
}

/**
 * Check if a given object implements the SuccessAvatarProfilesPayload interface.
 */
export function instanceOfSuccessAvatarProfilesPayload(value: object): value is SuccessAvatarProfilesPayload {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function SuccessAvatarProfilesPayloadFromJSON(json: any): SuccessAvatarProfilesPayload {
    return SuccessAvatarProfilesPayloadFromJSONTyped(json, false);
}

export function SuccessAvatarProfilesPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessAvatarProfilesPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AvatarProfilesPayloadFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
        'ok': json['ok'],
    };
}

export function SuccessAvatarProfilesPayloadToJSON(json: any): SuccessAvatarProfilesPayload {
    return SuccessAvatarProfilesPayloadToJSONTyped(json, false);
}

export function SuccessAvatarProfilesPayloadToJSONTyped(value?: SuccessAvatarProfilesPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AvatarProfilesPayloadToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
        'ok': value['ok'],
    };
}

