/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TiktokLabelBody
 */
export interface TiktokLabelBody {
    /**
     * 
     * @type {string}
     * @memberof TiktokLabelBody
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof TiktokLabelBody
     */
    label: string | null;
}

/**
 * Check if a given object implements the TiktokLabelBody interface.
 */
export function instanceOfTiktokLabelBody(value: object): value is TiktokLabelBody {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function TiktokLabelBodyFromJSON(json: any): TiktokLabelBody {
    return TiktokLabelBodyFromJSONTyped(json, false);
}

export function TiktokLabelBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TiktokLabelBody {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'label': json['label'],
    };
}

export function TiktokLabelBodyToJSON(json: any): TiktokLabelBody {
    return TiktokLabelBodyToJSONTyped(json, false);
}

export function TiktokLabelBodyToJSONTyped(value?: TiktokLabelBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'label': value['label'],
    };
}

