/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TiktokModelMapBody
 */
export interface TiktokModelMapBody {
    /**
     * 
     * @type {string}
     * @memberof TiktokModelMapBody
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof TiktokModelMapBody
     */
    connectedAccountId: string;
    /**
     * 
     * @type {string}
     * @memberof TiktokModelMapBody
     */
    modelId: string;
    /**
     * 
     * @type {string}
     * @memberof TiktokModelMapBody
     */
    remoteIdentityId: string | null;
}

/**
 * Check if a given object implements the TiktokModelMapBody interface.
 */
export function instanceOfTiktokModelMapBody(value: object): value is TiktokModelMapBody {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('connectedAccountId' in value) || value['connectedAccountId'] === undefined) return false;
    if (!('modelId' in value) || value['modelId'] === undefined) return false;
    if (!('remoteIdentityId' in value) || value['remoteIdentityId'] === undefined) return false;
    return true;
}

export function TiktokModelMapBodyFromJSON(json: any): TiktokModelMapBody {
    return TiktokModelMapBodyFromJSONTyped(json, false);
}

export function TiktokModelMapBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TiktokModelMapBody {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'connectedAccountId': json['connected_account_id'],
        'modelId': json['model_id'],
        'remoteIdentityId': json['remote_identity_id'],
    };
}

export function TiktokModelMapBodyToJSON(json: any): TiktokModelMapBody {
    return TiktokModelMapBodyToJSONTyped(json, false);
}

export function TiktokModelMapBodyToJSONTyped(value?: TiktokModelMapBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'connected_account_id': value['connectedAccountId'],
        'model_id': value['modelId'],
        'remote_identity_id': value['remoteIdentityId'],
    };
}

