/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowDetailResponse
 */
export interface WorkflowDetailResponse {
    /**
     * 
     * @type {Date}
     * @memberof WorkflowDetailResponse
     */
    createdAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDetailResponse
     */
    description: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowDetailResponse
     */
    engineSlugs: Array<string> | null;
    /**
     * 
     * @type {any}
     * @memberof WorkflowDetailResponse
     */
    graph: any | null;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDetailResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowDetailResponse
     */
    lastRunAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDetailResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDetailResponse
     */
    ownerOrgId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDetailResponse
     */
    ownerUserId: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowDetailResponse
     */
    runCount: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDetailResponse
     */
    status: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowDetailResponse
     */
    tags: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowDetailResponse
     */
    updatedAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof WorkflowDetailResponse
     */
    version: number;
}

/**
 * Check if a given object implements the WorkflowDetailResponse interface.
 */
export function instanceOfWorkflowDetailResponse(value: object): value is WorkflowDetailResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('engineSlugs' in value) || value['engineSlugs'] === undefined) return false;
    if (!('graph' in value) || value['graph'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastRunAt' in value) || value['lastRunAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ownerOrgId' in value) || value['ownerOrgId'] === undefined) return false;
    if (!('ownerUserId' in value) || value['ownerUserId'] === undefined) return false;
    if (!('runCount' in value) || value['runCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function WorkflowDetailResponseFromJSON(json: any): WorkflowDetailResponse {
    return WorkflowDetailResponseFromJSONTyped(json, false);
}

export function WorkflowDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'description': json['description'],
        'engineSlugs': json['engine_slugs'] == null ? null : json['engine_slugs'],
        'graph': json['graph'],
        'id': json['id'],
        'lastRunAt': (json['last_run_at'] == null ? null : new Date(json['last_run_at'])),
        'name': json['name'],
        'ownerOrgId': json['owner_org_id'],
        'ownerUserId': json['owner_user_id'],
        'runCount': json['run_count'],
        'status': json['status'],
        'tags': json['tags'] == null ? null : json['tags'],
        'updatedAt': (json['updated_at'] == null ? null : new Date(json['updated_at'])),
        'version': json['version'],
    };
}

export function WorkflowDetailResponseToJSON(json: any): WorkflowDetailResponse {
    return WorkflowDetailResponseToJSONTyped(json, false);
}

export function WorkflowDetailResponseToJSONTyped(value?: WorkflowDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': (value['createdAt'] == null ? null : (value['createdAt'] as any).toISOString()),
        'description': value['description'],
        'engine_slugs': value['engineSlugs'],
        'graph': value['graph'],
        'id': value['id'],
        'last_run_at': (value['lastRunAt'] == null ? null : (value['lastRunAt'] as any).toISOString()),
        'name': value['name'],
        'owner_org_id': value['ownerOrgId'],
        'owner_user_id': value['ownerUserId'],
        'run_count': value['runCount'],
        'status': value['status'],
        'tags': value['tags'],
        'updated_at': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
        'version': value['version'],
    };
}

