/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlbumCreateBody,
  AlbumItemCreateBody,
  AlbumItemIDBody,
  AlbumItemUpdateBody,
  AlbumItemsBulkBody,
  AlbumLinkBody,
  AlbumRevokeBody,
  AlbumShareBody,
  AlbumUpdateBody,
  SuccessAlbumBulkAddRes,
  SuccessAlbumDeleteRes,
  SuccessAlbumDetailResponse,
  SuccessAlbumItemDetail,
  SuccessAlbumItemSecretPayload,
  SuccessAlbumItemsPayload,
  SuccessAlbumResponse,
  SuccessAlbumRevokeRes,
  SuccessAlbumShareGrant,
  SuccessAlbumSharesPayload,
  SuccessPageAlbumResponse,
} from '../models/index';
import {
    AlbumCreateBodyFromJSON,
    AlbumCreateBodyToJSON,
    AlbumItemCreateBodyFromJSON,
    AlbumItemCreateBodyToJSON,
    AlbumItemIDBodyFromJSON,
    AlbumItemIDBodyToJSON,
    AlbumItemUpdateBodyFromJSON,
    AlbumItemUpdateBodyToJSON,
    AlbumItemsBulkBodyFromJSON,
    AlbumItemsBulkBodyToJSON,
    AlbumLinkBodyFromJSON,
    AlbumLinkBodyToJSON,
    AlbumRevokeBodyFromJSON,
    AlbumRevokeBodyToJSON,
    AlbumShareBodyFromJSON,
    AlbumShareBodyToJSON,
    AlbumUpdateBodyFromJSON,
    AlbumUpdateBodyToJSON,
    SuccessAlbumBulkAddResFromJSON,
    SuccessAlbumBulkAddResToJSON,
    SuccessAlbumDeleteResFromJSON,
    SuccessAlbumDeleteResToJSON,
    SuccessAlbumDetailResponseFromJSON,
    SuccessAlbumDetailResponseToJSON,
    SuccessAlbumItemDetailFromJSON,
    SuccessAlbumItemDetailToJSON,
    SuccessAlbumItemSecretPayloadFromJSON,
    SuccessAlbumItemSecretPayloadToJSON,
    SuccessAlbumItemsPayloadFromJSON,
    SuccessAlbumItemsPayloadToJSON,
    SuccessAlbumResponseFromJSON,
    SuccessAlbumResponseToJSON,
    SuccessAlbumRevokeResFromJSON,
    SuccessAlbumRevokeResToJSON,
    SuccessAlbumShareGrantFromJSON,
    SuccessAlbumShareGrantToJSON,
    SuccessAlbumSharesPayloadFromJSON,
    SuccessAlbumSharesPayloadToJSON,
    SuccessPageAlbumResponseFromJSON,
    SuccessPageAlbumResponseToJSON,
} from '../models/index';

export interface AddAlbumItemRequest {
    albumItemCreateBody?: AlbumItemCreateBody;
}

export interface AddAlbumItemsBulkRequest {
    albumItemsBulkBody?: AlbumItemsBulkBody;
}

export interface CreateAlbumRequest {
    albumCreateBody?: AlbumCreateBody;
}

export interface DeleteAlbumRequest {
    albumId: string;
}

export interface GetAlbumRequest {
    albumId: string;
}

export interface LinkAlbumRequest {
    albumLinkBody?: AlbumLinkBody;
}

export interface ListAlbumItemsRequest {
    albumId: string;
}

export interface ListAlbumSharesRequest {
    albumId: string;
}

export interface ListAlbumsRequest {
    page?: number;
    pageSize?: number;
    ownerType?: string;
    ownerId?: string;
    orgId?: string;
    modelId?: string;
    search?: string;
}

export interface ReadAlbumItemSecretRequest {
    itemId: string;
}

export interface RemoveAlbumItemRequest {
    albumItemIDBody?: AlbumItemIDBody;
}

export interface RevokeAlbumShareRequest {
    albumRevokeBody?: AlbumRevokeBody;
}

export interface ShareAlbumRequest {
    albumShareBody?: AlbumShareBody;
}

export interface UnlinkAlbumRequest {
    albumLinkBody?: AlbumLinkBody;
}

export interface UpdateAlbumRequest {
    albumId: string;
    albumUpdateBody?: AlbumUpdateBody;
}

export interface UpdateAlbumItemRequest {
    itemId: string;
    albumItemUpdateBody?: AlbumItemUpdateBody;
}

/**
 * AlbumsApi - interface
 * 
 * @export
 * @interface AlbumsApiInterface
 */
export interface AlbumsApiInterface {
    /**
     * 
     * @summary Add an item to an album
     * @param {AlbumItemCreateBody} [albumItemCreateBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    addAlbumItemRaw(requestParameters: AddAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemDetail>>;

    /**
     * Add an item to an album
     */
    addAlbumItem(requestParameters: AddAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemDetail>;

    /**
     * Adds one asset_ref item per unique, not-yet-linked asset_id. 201 when items were created, 200 when all were skipped.
     * @summary Bulk-add asset items to an album
     * @param {AlbumItemsBulkBody} [albumItemsBulkBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    addAlbumItemsBulkRaw(requestParameters: AddAlbumItemsBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumBulkAddRes>>;

    /**
     * Adds one asset_ref item per unique, not-yet-linked asset_id. 201 when items were created, 200 when all were skipped.
     * Bulk-add asset items to an album
     */
    addAlbumItemsBulk(requestParameters: AddAlbumItemsBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumBulkAddRes>;

    /**
     * 
     * @summary Create an album
     * @param {AlbumCreateBody} [albumCreateBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    createAlbumRaw(requestParameters: CreateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>>;

    /**
     * Create an album
     */
    createAlbum(requestParameters: CreateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse>;

    /**
     * 
     * @summary Soft-delete an album
     * @param {string} albumId album UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    deleteAlbumRaw(requestParameters: DeleteAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumDeleteRes>>;

    /**
     * Soft-delete an album
     */
    deleteAlbum(requestParameters: DeleteAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumDeleteRes>;

    /**
     * 
     * @summary Get a single album by id (with items)
     * @param {string} albumId album UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    getAlbumRaw(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumDetailResponse>>;

    /**
     * Get a single album by id (with items)
     */
    getAlbum(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumDetailResponse>;

    /**
     * 
     * @summary Link an album to a model
     * @param {AlbumLinkBody} [albumLinkBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    linkAlbumRaw(requestParameters: LinkAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>>;

    /**
     * Link an album to a model
     */
    linkAlbum(requestParameters: LinkAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse>;

    /**
     * 
     * @summary List the items in an album
     * @param {string} albumId album UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    listAlbumItemsRaw(requestParameters: ListAlbumItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemsPayload>>;

    /**
     * List the items in an album
     */
    listAlbumItems(requestParameters: ListAlbumItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemsPayload>;

    /**
     * 
     * @summary List the access grants for an album
     * @param {string} albumId album UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    listAlbumSharesRaw(requestParameters: ListAlbumSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumSharesPayload>>;

    /**
     * List the access grants for an album
     */
    listAlbumShares(requestParameters: ListAlbumSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumSharesPayload>;

    /**
     * Returns the paginated album list. Defaults to the caller\'s own albums; org_id requires membership.
     * @summary List the albums accessible to the caller (offset paginated)
     * @param {number} [page] 1-based page number (default 1)
     * @param {number} [pageSize] page size (default 20, max 100)
     * @param {string} [ownerType] filter by owner_type
     * @param {string} [ownerId] filter by owner_id (UUID)
     * @param {string} [orgId] filter by owning org (UUID); membership-gated
     * @param {string} [modelId] filter by model_id (UUID)
     * @param {string} [search] free-text search across album fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    listAlbumsRaw(requestParameters: ListAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageAlbumResponse>>;

    /**
     * Returns the paginated album list. Defaults to the caller\'s own albums; org_id requires membership.
     * List the albums accessible to the caller (offset paginated)
     */
    listAlbums(requestParameters: ListAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageAlbumResponse>;

    /**
     * 
     * @summary Read an album item\'s stored secret
     * @param {string} itemId item UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    readAlbumItemSecretRaw(requestParameters: ReadAlbumItemSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemSecretPayload>>;

    /**
     * Read an album item\'s stored secret
     */
    readAlbumItemSecret(requestParameters: ReadAlbumItemSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemSecretPayload>;

    /**
     * 
     * @summary Remove an album item
     * @param {AlbumItemIDBody} [albumItemIDBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    removeAlbumItemRaw(requestParameters: RemoveAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumDeleteRes>>;

    /**
     * Remove an album item
     */
    removeAlbumItem(requestParameters: RemoveAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumDeleteRes>;

    /**
     * 
     * @summary Revoke an album access grant
     * @param {AlbumRevokeBody} [albumRevokeBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    revokeAlbumShareRaw(requestParameters: RevokeAlbumShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumRevokeRes>>;

    /**
     * Revoke an album access grant
     */
    revokeAlbumShare(requestParameters: RevokeAlbumShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumRevokeRes>;

    /**
     * 
     * @summary Grant access to an album
     * @param {AlbumShareBody} [albumShareBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    shareAlbumRaw(requestParameters: ShareAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumShareGrant>>;

    /**
     * Grant access to an album
     */
    shareAlbum(requestParameters: ShareAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumShareGrant>;

    /**
     * 
     * @summary Unlink an album from a model
     * @param {AlbumLinkBody} [albumLinkBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    unlinkAlbumRaw(requestParameters: UnlinkAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>>;

    /**
     * Unlink an album from a model
     */
    unlinkAlbum(requestParameters: UnlinkAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse>;

    /**
     * 
     * @summary Update an album
     * @param {string} albumId album UUID
     * @param {AlbumUpdateBody} [albumUpdateBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    updateAlbumRaw(requestParameters: UpdateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>>;

    /**
     * Update an album
     */
    updateAlbum(requestParameters: UpdateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse>;

    /**
     * 
     * @summary Update an album item
     * @param {string} itemId album-item UUID
     * @param {AlbumItemUpdateBody} [albumItemUpdateBody] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlbumsApiInterface
     */
    updateAlbumItemRaw(requestParameters: UpdateAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemDetail>>;

    /**
     * Update an album item
     */
    updateAlbumItem(requestParameters: UpdateAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemDetail>;

}

/**
 * 
 */
export class AlbumsApi extends runtime.BaseAPI implements AlbumsApiInterface {

    /**
     * Add an item to an album
     */
    async addAlbumItemRaw(requestParameters: AddAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemDetail>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/items`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumItemCreateBodyToJSON(requestParameters['albumItemCreateBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumItemDetailFromJSON(jsonValue));
    }

    /**
     * Add an item to an album
     */
    async addAlbumItem(requestParameters: AddAlbumItemRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemDetail> {
        const response = await this.addAlbumItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds one asset_ref item per unique, not-yet-linked asset_id. 201 when items were created, 200 when all were skipped.
     * Bulk-add asset items to an album
     */
    async addAlbumItemsBulkRaw(requestParameters: AddAlbumItemsBulkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumBulkAddRes>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/items/bulk`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumItemsBulkBodyToJSON(requestParameters['albumItemsBulkBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumBulkAddResFromJSON(jsonValue));
    }

    /**
     * Adds one asset_ref item per unique, not-yet-linked asset_id. 201 when items were created, 200 when all were skipped.
     * Bulk-add asset items to an album
     */
    async addAlbumItemsBulk(requestParameters: AddAlbumItemsBulkRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumBulkAddRes> {
        const response = await this.addAlbumItemsBulkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an album
     */
    async createAlbumRaw(requestParameters: CreateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumCreateBodyToJSON(requestParameters['albumCreateBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumResponseFromJSON(jsonValue));
    }

    /**
     * Create an album
     */
    async createAlbum(requestParameters: CreateAlbumRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse> {
        const response = await this.createAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft-delete an album
     */
    async deleteAlbumRaw(requestParameters: DeleteAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumDeleteRes>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling deleteAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/{album_id}`.replace(`{${"album_id"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumDeleteResFromJSON(jsonValue));
    }

    /**
     * Soft-delete an album
     */
    async deleteAlbum(requestParameters: DeleteAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumDeleteRes> {
        const response = await this.deleteAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single album by id (with items)
     */
    async getAlbumRaw(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumDetailResponse>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling getAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/{album_id}`.replace(`{${"album_id"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get a single album by id (with items)
     */
    async getAlbum(requestParameters: GetAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumDetailResponse> {
        const response = await this.getAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Link an album to a model
     */
    async linkAlbumRaw(requestParameters: LinkAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/link`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumLinkBodyToJSON(requestParameters['albumLinkBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumResponseFromJSON(jsonValue));
    }

    /**
     * Link an album to a model
     */
    async linkAlbum(requestParameters: LinkAlbumRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse> {
        const response = await this.linkAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the items in an album
     */
    async listAlbumItemsRaw(requestParameters: ListAlbumItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemsPayload>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling listAlbumItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/{album_id}/items`.replace(`{${"album_id"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumItemsPayloadFromJSON(jsonValue));
    }

    /**
     * List the items in an album
     */
    async listAlbumItems(requestParameters: ListAlbumItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemsPayload> {
        const response = await this.listAlbumItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the access grants for an album
     */
    async listAlbumSharesRaw(requestParameters: ListAlbumSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumSharesPayload>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling listAlbumShares().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/{album_id}/shares`.replace(`{${"album_id"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumSharesPayloadFromJSON(jsonValue));
    }

    /**
     * List the access grants for an album
     */
    async listAlbumShares(requestParameters: ListAlbumSharesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumSharesPayload> {
        const response = await this.listAlbumSharesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the paginated album list. Defaults to the caller\'s own albums; org_id requires membership.
     * List the albums accessible to the caller (offset paginated)
     */
    async listAlbumsRaw(requestParameters: ListAlbumsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageAlbumResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['ownerType'] != null) {
            queryParameters['owner_type'] = requestParameters['ownerType'];
        }

        if (requestParameters['ownerId'] != null) {
            queryParameters['owner_id'] = requestParameters['ownerId'];
        }

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['modelId'] != null) {
            queryParameters['model_id'] = requestParameters['modelId'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessPageAlbumResponseFromJSON(jsonValue));
    }

    /**
     * Returns the paginated album list. Defaults to the caller\'s own albums; org_id requires membership.
     * List the albums accessible to the caller (offset paginated)
     */
    async listAlbums(requestParameters: ListAlbumsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageAlbumResponse> {
        const response = await this.listAlbumsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read an album item\'s stored secret
     */
    async readAlbumItemSecretRaw(requestParameters: ReadAlbumItemSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemSecretPayload>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling readAlbumItemSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/items/{item_id}/secret`.replace(`{${"item_id"}}`, encodeURIComponent(String(requestParameters['itemId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumItemSecretPayloadFromJSON(jsonValue));
    }

    /**
     * Read an album item\'s stored secret
     */
    async readAlbumItemSecret(requestParameters: ReadAlbumItemSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemSecretPayload> {
        const response = await this.readAlbumItemSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove an album item
     */
    async removeAlbumItemRaw(requestParameters: RemoveAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumDeleteRes>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/items/remove`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumItemIDBodyToJSON(requestParameters['albumItemIDBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumDeleteResFromJSON(jsonValue));
    }

    /**
     * Remove an album item
     */
    async removeAlbumItem(requestParameters: RemoveAlbumItemRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumDeleteRes> {
        const response = await this.removeAlbumItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke an album access grant
     */
    async revokeAlbumShareRaw(requestParameters: RevokeAlbumShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumRevokeRes>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/revoke`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumRevokeBodyToJSON(requestParameters['albumRevokeBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumRevokeResFromJSON(jsonValue));
    }

    /**
     * Revoke an album access grant
     */
    async revokeAlbumShare(requestParameters: RevokeAlbumShareRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumRevokeRes> {
        const response = await this.revokeAlbumShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Grant access to an album
     */
    async shareAlbumRaw(requestParameters: ShareAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumShareGrant>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/share`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumShareBodyToJSON(requestParameters['albumShareBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumShareGrantFromJSON(jsonValue));
    }

    /**
     * Grant access to an album
     */
    async shareAlbum(requestParameters: ShareAlbumRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumShareGrant> {
        const response = await this.shareAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unlink an album from a model
     */
    async unlinkAlbumRaw(requestParameters: UnlinkAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/unlink`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumLinkBodyToJSON(requestParameters['albumLinkBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumResponseFromJSON(jsonValue));
    }

    /**
     * Unlink an album from a model
     */
    async unlinkAlbum(requestParameters: UnlinkAlbumRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse> {
        const response = await this.unlinkAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an album
     */
    async updateAlbumRaw(requestParameters: UpdateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumResponse>> {
        if (requestParameters['albumId'] == null) {
            throw new runtime.RequiredError(
                'albumId',
                'Required parameter "albumId" was null or undefined when calling updateAlbum().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/{album_id}`.replace(`{${"album_id"}}`, encodeURIComponent(String(requestParameters['albumId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumUpdateBodyToJSON(requestParameters['albumUpdateBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumResponseFromJSON(jsonValue));
    }

    /**
     * Update an album
     */
    async updateAlbum(requestParameters: UpdateAlbumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumResponse> {
        const response = await this.updateAlbumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an album item
     */
    async updateAlbumItemRaw(requestParameters: UpdateAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAlbumItemDetail>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling updateAlbumItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/albums/items/{item_id}`.replace(`{${"item_id"}}`, encodeURIComponent(String(requestParameters['itemId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AlbumItemUpdateBodyToJSON(requestParameters['albumItemUpdateBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAlbumItemDetailFromJSON(jsonValue));
    }

    /**
     * Update an album item
     */
    async updateAlbumItem(requestParameters: UpdateAlbumItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAlbumItemDetail> {
        const response = await this.updateAlbumItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
