/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SuccessAppAccessResponse,
  SuccessAppLatestVersionResponse,
  SuccessPageAppCatalogItem,
  SuccessPageAppVersionPublicResponse,
} from '../models/index';
import {
    SuccessAppAccessResponseFromJSON,
    SuccessAppAccessResponseToJSON,
    SuccessAppLatestVersionResponseFromJSON,
    SuccessAppLatestVersionResponseToJSON,
    SuccessPageAppCatalogItemFromJSON,
    SuccessPageAppCatalogItemToJSON,
    SuccessPageAppVersionPublicResponseFromJSON,
    SuccessPageAppVersionPublicResponseToJSON,
} from '../models/index';

export interface GetAppAccessRequest {
    appSlug: string;
}

export interface GetAppLatestVersionRequest {
    appSlug: string;
}

export interface ListAppVersionsRequest {
    appSlug: string;
    page?: number;
    pageSize?: number;
    publishedOnly?: string;
}

export interface ListAppsRequest {
    page?: number;
    pageSize?: number;
    includeInactive?: string;
    q?: string;
}

/**
 * AppsApi - interface
 * 
 * @export
 * @interface AppsApiInterface
 */
export interface AppsApiInterface {
    /**
     * 
     * @summary Check the caller\'s access to an application
     * @param {string} appSlug application slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppsApiInterface
     */
    getAppAccessRaw(requestParameters: GetAppAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAppAccessResponse>>;

    /**
     * Check the caller\'s access to an application
     */
    getAppAccess(requestParameters: GetAppAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAppAccessResponse>;

    /**
     * Returns the latest published version + downloads for an application the caller can access. A denied access gate returns 403.
     * @summary Get the latest published version of an application
     * @param {string} appSlug application slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppsApiInterface
     */
    getAppLatestVersionRaw(requestParameters: GetAppLatestVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAppLatestVersionResponse>>;

    /**
     * Returns the latest published version + downloads for an application the caller can access. A denied access gate returns 403.
     * Get the latest published version of an application
     */
    getAppLatestVersion(requestParameters: GetAppLatestVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAppLatestVersionResponse>;

    /**
     * Returns the paginated version history for an application the caller can access. A denied access gate returns 403.
     * @summary List the versions of an application (offset paginated)
     * @param {string} appSlug application slug
     * @param {number} [page] 1-based page number (default 1)
     * @param {number} [pageSize] page size (default 20, max 100)
     * @param {string} [publishedOnly] set to 0/false/no to include unpublished versions (default true)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppsApiInterface
     */
    listAppVersionsRaw(requestParameters: ListAppVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageAppVersionPublicResponse>>;

    /**
     * Returns the paginated version history for an application the caller can access. A denied access gate returns 403.
     * List the versions of an application (offset paginated)
     */
    listAppVersions(requestParameters: ListAppVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageAppVersionPublicResponse>;

    /**
     * Returns the application catalog filtered to the entries the caller has an active access grant for, with each app\'s latest published version + downloads.
     * @summary List the applications the caller can access (offset paginated)
     * @param {number} [page] 1-based page number (default 1)
     * @param {number} [pageSize] page size (default 20, max 100)
     * @param {string} [includeInactive] set to 1/true/yes to include inactive applications
     * @param {string} [q] free-text search across slug/name/description
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppsApiInterface
     */
    listAppsRaw(requestParameters: ListAppsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageAppCatalogItem>>;

    /**
     * Returns the application catalog filtered to the entries the caller has an active access grant for, with each app\'s latest published version + downloads.
     * List the applications the caller can access (offset paginated)
     */
    listApps(requestParameters: ListAppsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageAppCatalogItem>;

}

/**
 * 
 */
export class AppsApi extends runtime.BaseAPI implements AppsApiInterface {

    /**
     * Check the caller\'s access to an application
     */
    async getAppAccessRaw(requestParameters: GetAppAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAppAccessResponse>> {
        if (requestParameters['appSlug'] == null) {
            throw new runtime.RequiredError(
                'appSlug',
                'Required parameter "appSlug" was null or undefined when calling getAppAccess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/apps/{app_slug}/access`.replace(`{${"app_slug"}}`, encodeURIComponent(String(requestParameters['appSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAppAccessResponseFromJSON(jsonValue));
    }

    /**
     * Check the caller\'s access to an application
     */
    async getAppAccess(requestParameters: GetAppAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAppAccessResponse> {
        const response = await this.getAppAccessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the latest published version + downloads for an application the caller can access. A denied access gate returns 403.
     * Get the latest published version of an application
     */
    async getAppLatestVersionRaw(requestParameters: GetAppLatestVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessAppLatestVersionResponse>> {
        if (requestParameters['appSlug'] == null) {
            throw new runtime.RequiredError(
                'appSlug',
                'Required parameter "appSlug" was null or undefined when calling getAppLatestVersion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/apps/{app_slug}/versions/latest`.replace(`{${"app_slug"}}`, encodeURIComponent(String(requestParameters['appSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessAppLatestVersionResponseFromJSON(jsonValue));
    }

    /**
     * Returns the latest published version + downloads for an application the caller can access. A denied access gate returns 403.
     * Get the latest published version of an application
     */
    async getAppLatestVersion(requestParameters: GetAppLatestVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessAppLatestVersionResponse> {
        const response = await this.getAppLatestVersionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the paginated version history for an application the caller can access. A denied access gate returns 403.
     * List the versions of an application (offset paginated)
     */
    async listAppVersionsRaw(requestParameters: ListAppVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageAppVersionPublicResponse>> {
        if (requestParameters['appSlug'] == null) {
            throw new runtime.RequiredError(
                'appSlug',
                'Required parameter "appSlug" was null or undefined when calling listAppVersions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['publishedOnly'] != null) {
            queryParameters['published_only'] = requestParameters['publishedOnly'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/apps/{app_slug}/versions`.replace(`{${"app_slug"}}`, encodeURIComponent(String(requestParameters['appSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessPageAppVersionPublicResponseFromJSON(jsonValue));
    }

    /**
     * Returns the paginated version history for an application the caller can access. A denied access gate returns 403.
     * List the versions of an application (offset paginated)
     */
    async listAppVersions(requestParameters: ListAppVersionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageAppVersionPublicResponse> {
        const response = await this.listAppVersionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the application catalog filtered to the entries the caller has an active access grant for, with each app\'s latest published version + downloads.
     * List the applications the caller can access (offset paginated)
     */
    async listAppsRaw(requestParameters: ListAppsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageAppCatalogItem>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['includeInactive'] != null) {
            queryParameters['include_inactive'] = requestParameters['includeInactive'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/apps`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessPageAppCatalogItemFromJSON(jsonValue));
    }

    /**
     * Returns the application catalog filtered to the entries the caller has an active access grant for, with each app\'s latest published version + downloads.
     * List the applications the caller can access (offset paginated)
     */
    async listApps(requestParameters: ListAppsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageAppCatalogItem> {
        const response = await this.listAppsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
