/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SuccessListProduct,
  SuccessPageOrder,
  SuccessSubscription,
  SuccessSummary,
} from '../models/index';
import {
    SuccessListProductFromJSON,
    SuccessListProductToJSON,
    SuccessPageOrderFromJSON,
    SuccessPageOrderToJSON,
    SuccessSubscriptionFromJSON,
    SuccessSubscriptionToJSON,
    SuccessSummaryFromJSON,
    SuccessSummaryToJSON,
} from '../models/index';

export interface ListBillingInvoicesRequest {
    page?: number;
    pageSize?: number;
}

/**
 * BillingApi - interface
 * 
 * @export
 * @interface BillingApiInterface
 */
export interface BillingApiInterface {
    /**
     * Returns the caller\'s active subscription, or 404 when none is active.
     * @summary Get the caller\'s active subscription
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getBillingSubscriptionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSubscription>>;

    /**
     * Returns the caller\'s active subscription, or 404 when none is active.
     * Get the caller\'s active subscription
     */
    getBillingSubscription(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSubscription>;

    /**
     * Returns the caller\'s wallet + subscription + plan summary.
     * @summary Get the caller\'s billing summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getBillingSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSummary>>;

    /**
     * Returns the caller\'s wallet + subscription + plan summary.
     * Get the caller\'s billing summary
     */
    getBillingSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSummary>;

    /**
     * Returns the paginated invoice/order history for the caller.
     * @summary List the caller\'s invoices (offset paginated)
     * @param {number} [page] 1-based page number (default 1)
     * @param {number} [pageSize] page size (default 20, max 100)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listBillingInvoicesRaw(requestParameters: ListBillingInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageOrder>>;

    /**
     * Returns the paginated invoice/order history for the caller.
     * List the caller\'s invoices (offset paginated)
     */
    listBillingInvoices(requestParameters: ListBillingInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageOrder>;

    /**
     * Returns the Stripe-backed product catalog. Cached at the edge for 1h (private, keyed on Authorization).
     * @summary List the purchasable products + prices
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listBillingProductsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessListProduct>>;

    /**
     * Returns the Stripe-backed product catalog. Cached at the edge for 1h (private, keyed on Authorization).
     * List the purchasable products + prices
     */
    listBillingProducts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessListProduct>;

}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI implements BillingApiInterface {

    /**
     * Returns the caller\'s active subscription, or 404 when none is active.
     * Get the caller\'s active subscription
     */
    async getBillingSubscriptionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSubscription>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/billing/subscription`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSubscriptionFromJSON(jsonValue));
    }

    /**
     * Returns the caller\'s active subscription, or 404 when none is active.
     * Get the caller\'s active subscription
     */
    async getBillingSubscription(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSubscription> {
        const response = await this.getBillingSubscriptionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the caller\'s wallet + subscription + plan summary.
     * Get the caller\'s billing summary
     */
    async getBillingSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSummary>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/billing/summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSummaryFromJSON(jsonValue));
    }

    /**
     * Returns the caller\'s wallet + subscription + plan summary.
     * Get the caller\'s billing summary
     */
    async getBillingSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSummary> {
        const response = await this.getBillingSummaryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the paginated invoice/order history for the caller.
     * List the caller\'s invoices (offset paginated)
     */
    async listBillingInvoicesRaw(requestParameters: ListBillingInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessPageOrder>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/billing/invoices`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessPageOrderFromJSON(jsonValue));
    }

    /**
     * Returns the paginated invoice/order history for the caller.
     * List the caller\'s invoices (offset paginated)
     */
    async listBillingInvoices(requestParameters: ListBillingInvoicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessPageOrder> {
        const response = await this.listBillingInvoicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the Stripe-backed product catalog. Cached at the edge for 1h (private, keyed on Authorization).
     * List the purchasable products + prices
     */
    async listBillingProductsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessListProduct>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/billing/products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessListProductFromJSON(jsonValue));
    }

    /**
     * Returns the Stripe-backed product catalog. Cached at the edge for 1h (private, keyed on Authorization).
     * List the purchasable products + prices
     */
    async listBillingProducts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessListProduct> {
        const response = await this.listBillingProductsRaw(initOverrides);
        return await response.value();
    }

}
