/* tslint:disable */
/* eslint-disable */
/**
 * Inoue AI
 * Inoue AI SaaS Backend (Go rewrite)
 *
 * The version of the OpenAPI document: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SuccessCodeResponse,
  SuccessListCodeResponse,
  SuccessSummaryResult,
} from '../models/index';
import {
    SuccessCodeResponseFromJSON,
    SuccessCodeResponseToJSON,
    SuccessListCodeResponseFromJSON,
    SuccessListCodeResponseToJSON,
    SuccessSummaryResultFromJSON,
    SuccessSummaryResultToJSON,
} from '../models/index';

export interface RevokeReferralCodeRequest {
    codeId: string;
}

/**
 * ReferralsApi - interface
 * 
 * @export
 * @interface ReferralsApiInterface
 */
export interface ReferralsApiInterface {
    /**
     * 
     * @summary Create a referral code
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReferralsApiInterface
     */
    createReferralCodeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessCodeResponse>>;

    /**
     * Create a referral code
     */
    createReferralCode(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessCodeResponse>;

    /**
     * Returns the per-user referral summary the dashboard hero card renders (rewards earned, referred users, active codes).
     * @summary Get the caller\'s referral summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReferralsApiInterface
     */
    getReferralSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSummaryResult>>;

    /**
     * Returns the per-user referral summary the dashboard hero card renders (rewards earned, referred users, active codes).
     * Get the caller\'s referral summary
     */
    getReferralSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSummaryResult>;

    /**
     * 
     * @summary List the caller\'s referral codes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReferralsApiInterface
     */
    listReferralCodesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessListCodeResponse>>;

    /**
     * List the caller\'s referral codes
     */
    listReferralCodes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessListCodeResponse>;

    /**
     * 
     * @summary Revoke a referral code
     * @param {string} codeId referral-code UUID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReferralsApiInterface
     */
    revokeReferralCodeRaw(requestParameters: RevokeReferralCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessCodeResponse>>;

    /**
     * Revoke a referral code
     */
    revokeReferralCode(requestParameters: RevokeReferralCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessCodeResponse>;

}

/**
 * 
 */
export class ReferralsApi extends runtime.BaseAPI implements ReferralsApiInterface {

    /**
     * Create a referral code
     */
    async createReferralCodeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessCodeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/referrals/codes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessCodeResponseFromJSON(jsonValue));
    }

    /**
     * Create a referral code
     */
    async createReferralCode(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessCodeResponse> {
        const response = await this.createReferralCodeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns the per-user referral summary the dashboard hero card renders (rewards earned, referred users, active codes).
     * Get the caller\'s referral summary
     */
    async getReferralSummaryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessSummaryResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/referrals/summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessSummaryResultFromJSON(jsonValue));
    }

    /**
     * Returns the per-user referral summary the dashboard hero card renders (rewards earned, referred users, active codes).
     * Get the caller\'s referral summary
     */
    async getReferralSummary(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessSummaryResult> {
        const response = await this.getReferralSummaryRaw(initOverrides);
        return await response.value();
    }

    /**
     * List the caller\'s referral codes
     */
    async listReferralCodesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessListCodeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/referrals/codes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessListCodeResponseFromJSON(jsonValue));
    }

    /**
     * List the caller\'s referral codes
     */
    async listReferralCodes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessListCodeResponse> {
        const response = await this.listReferralCodesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Revoke a referral code
     */
    async revokeReferralCodeRaw(requestParameters: RevokeReferralCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuccessCodeResponse>> {
        if (requestParameters['codeId'] == null) {
            throw new runtime.RequiredError(
                'codeId',
                'Required parameter "codeId" was null or undefined when calling revokeReferralCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/referrals/codes/{code_id}/revoke`.replace(`{${"code_id"}}`, encodeURIComponent(String(requestParameters['codeId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessCodeResponseFromJSON(jsonValue));
    }

    /**
     * Revoke a referral code
     */
    async revokeReferralCode(requestParameters: RevokeReferralCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuccessCodeResponse> {
        const response = await this.revokeReferralCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
