# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from inoue_ai_sdk.models.flux_options import FluxOptions
from inoue_ai_sdk.models.nano_banana_options import NanoBananaOptions
from inoue_ai_sdk.models.seedream_options import SeedreamOptions
from inoue_ai_sdk.models.topaz_options import TopazOptions
from typing import Optional, Set
from typing_extensions import Self

class EnumsResponse(BaseModel):
    """
    EnumsResponse
    """ # noqa: E501
    access_levels: List[StrictStr]
    asset_types: List[StrictStr]
    engine_categories: List[StrictStr]
    engine_category_map: Dict[str, List[StrictStr]]
    engine_types: List[StrictStr]
    flux_options: FluxOptions
    grantee_types: List[StrictStr]
    identity_asset_roles: List[StrictStr]
    job_statuses: List[StrictStr]
    job_type_titles: Dict[str, StrictStr]
    job_types: List[StrictStr]
    membership_statuses: List[StrictStr]
    model_creation_modes: List[StrictStr]
    nanobanana_options: NanoBananaOptions
    org_roles: List[StrictStr]
    platforms: List[StrictStr]
    post_statuses: List[StrictStr]
    post_target_statuses: List[StrictStr]
    prompt_generators: List[Dict[str, Any]]
    prompt_run_engine_types: List[StrictStr]
    prompt_run_job_types: List[StrictStr]
    prompt_template_schemas: List[Dict[str, Any]]
    resource_types: List[StrictStr]
    seedream_options: SeedreamOptions
    topaz_options: TopazOptions
    vision_generation_schemas: List[Dict[str, Any]]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["access_levels", "asset_types", "engine_categories", "engine_category_map", "engine_types", "flux_options", "grantee_types", "identity_asset_roles", "job_statuses", "job_type_titles", "job_types", "membership_statuses", "model_creation_modes", "nanobanana_options", "org_roles", "platforms", "post_statuses", "post_target_statuses", "prompt_generators", "prompt_run_engine_types", "prompt_run_job_types", "prompt_template_schemas", "resource_types", "seedream_options", "topaz_options", "vision_generation_schemas"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnumsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of flux_options
        if self.flux_options:
            _dict['flux_options'] = self.flux_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nanobanana_options
        if self.nanobanana_options:
            _dict['nanobanana_options'] = self.nanobanana_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of seedream_options
        if self.seedream_options:
            _dict['seedream_options'] = self.seedream_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of topaz_options
        if self.topaz_options:
            _dict['topaz_options'] = self.topaz_options.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnumsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_levels": obj.get("access_levels"),
            "asset_types": obj.get("asset_types"),
            "engine_categories": obj.get("engine_categories"),
            "engine_category_map": obj.get("engine_category_map"),
            "engine_types": obj.get("engine_types"),
            "flux_options": FluxOptions.from_dict(obj["flux_options"]) if obj.get("flux_options") is not None else None,
            "grantee_types": obj.get("grantee_types"),
            "identity_asset_roles": obj.get("identity_asset_roles"),
            "job_statuses": obj.get("job_statuses"),
            "job_type_titles": obj.get("job_type_titles"),
            "job_types": obj.get("job_types"),
            "membership_statuses": obj.get("membership_statuses"),
            "model_creation_modes": obj.get("model_creation_modes"),
            "nanobanana_options": NanoBananaOptions.from_dict(obj["nanobanana_options"]) if obj.get("nanobanana_options") is not None else None,
            "org_roles": obj.get("org_roles"),
            "platforms": obj.get("platforms"),
            "post_statuses": obj.get("post_statuses"),
            "post_target_statuses": obj.get("post_target_statuses"),
            "prompt_generators": obj.get("prompt_generators"),
            "prompt_run_engine_types": obj.get("prompt_run_engine_types"),
            "prompt_run_job_types": obj.get("prompt_run_job_types"),
            "prompt_template_schemas": obj.get("prompt_template_schemas"),
            "resource_types": obj.get("resource_types"),
            "seedream_options": SeedreamOptions.from_dict(obj["seedream_options"]) if obj.get("seedream_options") is not None else None,
            "topaz_options": TopazOptions.from_dict(obj["topaz_options"]) if obj.get("topaz_options") is not None else None,
            "vision_generation_schemas": obj.get("vision_generation_schemas")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


