# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JobResponse(BaseModel):
    """
    JobResponse
    """ # noqa: E501
    bill_failed_by_compute_seconds: Optional[StrictBool] = None
    claimed_at: Optional[datetime]
    claimed_by_worker_id: StrictStr
    compute_seconds: Optional[StrictInt] = None
    cost_credits: Optional[StrictStr] = None
    created_at: Optional[datetime]
    dispatched_at: Optional[datetime]
    engine_type: Optional[StrictStr]
    error_json: Optional[Any] = None
    finished_at: Optional[datetime]
    id: StrictStr
    input_json: Optional[Any] = None
    job_type: StrictStr
    last_heartbeat_at: Optional[datetime]
    model_id: StrictStr
    model_name: Optional[StrictStr]
    pipeline_run_id: StrictStr
    progress_json: Optional[Any] = None
    prompt_run_id: StrictStr
    requested_by_email: Optional[StrictStr]
    requested_by_user_id: StrictStr
    started_at: Optional[datetime]
    status: StrictStr
    template_id: Optional[StrictStr] = None
    template_title: Optional[StrictStr] = None
    updated_at: Optional[datetime]
    workflow_run_step_id: StrictStr
    __properties: ClassVar[List[str]] = ["bill_failed_by_compute_seconds", "claimed_at", "claimed_by_worker_id", "compute_seconds", "cost_credits", "created_at", "dispatched_at", "engine_type", "error_json", "finished_at", "id", "input_json", "job_type", "last_heartbeat_at", "model_id", "model_name", "pipeline_run_id", "progress_json", "prompt_run_id", "requested_by_email", "requested_by_user_id", "started_at", "status", "template_id", "template_title", "updated_at", "workflow_run_step_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if claimed_at (nullable) is None
        # and model_fields_set contains the field
        if self.claimed_at is None and "claimed_at" in self.model_fields_set:
            _dict['claimed_at'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if dispatched_at (nullable) is None
        # and model_fields_set contains the field
        if self.dispatched_at is None and "dispatched_at" in self.model_fields_set:
            _dict['dispatched_at'] = None

        # set to None if engine_type (nullable) is None
        # and model_fields_set contains the field
        if self.engine_type is None and "engine_type" in self.model_fields_set:
            _dict['engine_type'] = None

        # set to None if error_json (nullable) is None
        # and model_fields_set contains the field
        if self.error_json is None and "error_json" in self.model_fields_set:
            _dict['error_json'] = None

        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finished_at'] = None

        # set to None if input_json (nullable) is None
        # and model_fields_set contains the field
        if self.input_json is None and "input_json" in self.model_fields_set:
            _dict['input_json'] = None

        # set to None if last_heartbeat_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_heartbeat_at is None and "last_heartbeat_at" in self.model_fields_set:
            _dict['last_heartbeat_at'] = None

        # set to None if model_name (nullable) is None
        # and model_fields_set contains the field
        if self.model_name is None and "model_name" in self.model_fields_set:
            _dict['model_name'] = None

        # set to None if progress_json (nullable) is None
        # and model_fields_set contains the field
        if self.progress_json is None and "progress_json" in self.model_fields_set:
            _dict['progress_json'] = None

        # set to None if requested_by_email (nullable) is None
        # and model_fields_set contains the field
        if self.requested_by_email is None and "requested_by_email" in self.model_fields_set:
            _dict['requested_by_email'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bill_failed_by_compute_seconds": obj.get("bill_failed_by_compute_seconds"),
            "claimed_at": obj.get("claimed_at"),
            "claimed_by_worker_id": obj.get("claimed_by_worker_id"),
            "compute_seconds": obj.get("compute_seconds"),
            "cost_credits": obj.get("cost_credits"),
            "created_at": obj.get("created_at"),
            "dispatched_at": obj.get("dispatched_at"),
            "engine_type": obj.get("engine_type"),
            "error_json": obj.get("error_json"),
            "finished_at": obj.get("finished_at"),
            "id": obj.get("id"),
            "input_json": obj.get("input_json"),
            "job_type": obj.get("job_type"),
            "last_heartbeat_at": obj.get("last_heartbeat_at"),
            "model_id": obj.get("model_id"),
            "model_name": obj.get("model_name"),
            "pipeline_run_id": obj.get("pipeline_run_id"),
            "progress_json": obj.get("progress_json"),
            "prompt_run_id": obj.get("prompt_run_id"),
            "requested_by_email": obj.get("requested_by_email"),
            "requested_by_user_id": obj.get("requested_by_user_id"),
            "started_at": obj.get("started_at"),
            "status": obj.get("status"),
            "template_id": obj.get("template_id"),
            "template_title": obj.get("template_title"),
            "updated_at": obj.get("updated_at"),
            "workflow_run_step_id": obj.get("workflow_run_step_id")
        })
        return _obj


