# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from inoue_ai_sdk.models.model_stats import ModelStats
from typing import Optional, Set
from typing_extensions import Self

class ModelResponse(BaseModel):
    """
    ModelResponse
    """ # noqa: E501
    base_lora_id: Optional[StrictStr]
    canonical_body_image_url: Optional[StrictStr]
    canonical_candidate_id: StrictStr
    canonical_face_image_url: Optional[StrictStr]
    canonical_provenance: Optional[Any] = None
    canonical_source: Optional[StrictStr]
    created_at: Optional[datetime]
    creation_mode: Optional[StrictStr]
    description: Optional[StrictStr]
    hf_api_key_id: StrictStr
    hf_repo_is_private: Optional[StrictBool]
    hf_repo_url: Optional[StrictStr]
    id: StrictStr
    identity_lora_artifact_id: StrictStr
    identity_ready: Optional[StrictBool]
    lora_upload_asset_id: StrictStr
    lora_upload_metadata: Optional[Any] = None
    name: StrictStr
    owner_org_id: StrictStr
    owner_user_id: StrictStr
    stats: Optional[ModelStats] = None
    status: Optional[StrictStr]
    traits_spec: Optional[Any] = None
    updated_at: Optional[datetime]
    __properties: ClassVar[List[str]] = ["base_lora_id", "canonical_body_image_url", "canonical_candidate_id", "canonical_face_image_url", "canonical_provenance", "canonical_source", "created_at", "creation_mode", "description", "hf_api_key_id", "hf_repo_is_private", "hf_repo_url", "id", "identity_lora_artifact_id", "identity_ready", "lora_upload_asset_id", "lora_upload_metadata", "name", "owner_org_id", "owner_user_id", "stats", "status", "traits_spec", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of stats
        if self.stats:
            _dict['stats'] = self.stats.to_dict()
        # set to None if base_lora_id (nullable) is None
        # and model_fields_set contains the field
        if self.base_lora_id is None and "base_lora_id" in self.model_fields_set:
            _dict['base_lora_id'] = None

        # set to None if canonical_body_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.canonical_body_image_url is None and "canonical_body_image_url" in self.model_fields_set:
            _dict['canonical_body_image_url'] = None

        # set to None if canonical_face_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.canonical_face_image_url is None and "canonical_face_image_url" in self.model_fields_set:
            _dict['canonical_face_image_url'] = None

        # set to None if canonical_provenance (nullable) is None
        # and model_fields_set contains the field
        if self.canonical_provenance is None and "canonical_provenance" in self.model_fields_set:
            _dict['canonical_provenance'] = None

        # set to None if canonical_source (nullable) is None
        # and model_fields_set contains the field
        if self.canonical_source is None and "canonical_source" in self.model_fields_set:
            _dict['canonical_source'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if creation_mode (nullable) is None
        # and model_fields_set contains the field
        if self.creation_mode is None and "creation_mode" in self.model_fields_set:
            _dict['creation_mode'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if hf_repo_is_private (nullable) is None
        # and model_fields_set contains the field
        if self.hf_repo_is_private is None and "hf_repo_is_private" in self.model_fields_set:
            _dict['hf_repo_is_private'] = None

        # set to None if hf_repo_url (nullable) is None
        # and model_fields_set contains the field
        if self.hf_repo_url is None and "hf_repo_url" in self.model_fields_set:
            _dict['hf_repo_url'] = None

        # set to None if identity_ready (nullable) is None
        # and model_fields_set contains the field
        if self.identity_ready is None and "identity_ready" in self.model_fields_set:
            _dict['identity_ready'] = None

        # set to None if lora_upload_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.lora_upload_metadata is None and "lora_upload_metadata" in self.model_fields_set:
            _dict['lora_upload_metadata'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if traits_spec (nullable) is None
        # and model_fields_set contains the field
        if self.traits_spec is None and "traits_spec" in self.model_fields_set:
            _dict['traits_spec'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "base_lora_id": obj.get("base_lora_id"),
            "canonical_body_image_url": obj.get("canonical_body_image_url"),
            "canonical_candidate_id": obj.get("canonical_candidate_id"),
            "canonical_face_image_url": obj.get("canonical_face_image_url"),
            "canonical_provenance": obj.get("canonical_provenance"),
            "canonical_source": obj.get("canonical_source"),
            "created_at": obj.get("created_at"),
            "creation_mode": obj.get("creation_mode"),
            "description": obj.get("description"),
            "hf_api_key_id": obj.get("hf_api_key_id"),
            "hf_repo_is_private": obj.get("hf_repo_is_private"),
            "hf_repo_url": obj.get("hf_repo_url"),
            "id": obj.get("id"),
            "identity_lora_artifact_id": obj.get("identity_lora_artifact_id"),
            "identity_ready": obj.get("identity_ready"),
            "lora_upload_asset_id": obj.get("lora_upload_asset_id"),
            "lora_upload_metadata": obj.get("lora_upload_metadata"),
            "name": obj.get("name"),
            "owner_org_id": obj.get("owner_org_id"),
            "owner_user_id": obj.get("owner_user_id"),
            "stats": ModelStats.from_dict(obj["stats"]) if obj.get("stats") is not None else None,
            "status": obj.get("status"),
            "traits_spec": obj.get("traits_spec"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


