# coding: utf-8

"""
    Inoue AI

    Inoue AI SaaS Backend (Go rewrite)

    The version of the OpenAPI document: dev
    Contact: engineering@inoue.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from inoue_ai_sdk.models.video_job_link import VideoJobLink
from typing import Optional, Set
from typing_extensions import Self

class Video(BaseModel):
    """
    Video
    """ # noqa: E501
    comment_count: Optional[StrictInt]
    connected_account_id: StrictStr
    cover_url: Optional[StrictStr]
    created_at: Optional[datetime]
    description: Optional[StrictStr]
    duration_seconds: Optional[StrictInt]
    id: StrictStr
    like_count: Optional[StrictInt]
    linked_jobs: Optional[List[VideoJobLink]]
    model_id: StrictStr
    published_at: Optional[datetime]
    remote_video_id: StrictStr
    save_count: Optional[StrictInt]
    share_count: Optional[StrictInt]
    share_url: Optional[StrictStr]
    title: Optional[StrictStr]
    updated_at: Optional[datetime]
    view_count: Optional[StrictInt]
    watch_time_seconds: Optional[StrictInt]
    __properties: ClassVar[List[str]] = ["comment_count", "connected_account_id", "cover_url", "created_at", "description", "duration_seconds", "id", "like_count", "linked_jobs", "model_id", "published_at", "remote_video_id", "save_count", "share_count", "share_url", "title", "updated_at", "view_count", "watch_time_seconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Video from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in linked_jobs (list)
        _items = []
        if self.linked_jobs:
            for _item_linked_jobs in self.linked_jobs:
                if _item_linked_jobs:
                    _items.append(_item_linked_jobs.to_dict())
            _dict['linked_jobs'] = _items
        # set to None if comment_count (nullable) is None
        # and model_fields_set contains the field
        if self.comment_count is None and "comment_count" in self.model_fields_set:
            _dict['comment_count'] = None

        # set to None if cover_url (nullable) is None
        # and model_fields_set contains the field
        if self.cover_url is None and "cover_url" in self.model_fields_set:
            _dict['cover_url'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.duration_seconds is None and "duration_seconds" in self.model_fields_set:
            _dict['duration_seconds'] = None

        # set to None if like_count (nullable) is None
        # and model_fields_set contains the field
        if self.like_count is None and "like_count" in self.model_fields_set:
            _dict['like_count'] = None

        # set to None if linked_jobs (nullable) is None
        # and model_fields_set contains the field
        if self.linked_jobs is None and "linked_jobs" in self.model_fields_set:
            _dict['linked_jobs'] = None

        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['published_at'] = None

        # set to None if save_count (nullable) is None
        # and model_fields_set contains the field
        if self.save_count is None and "save_count" in self.model_fields_set:
            _dict['save_count'] = None

        # set to None if share_count (nullable) is None
        # and model_fields_set contains the field
        if self.share_count is None and "share_count" in self.model_fields_set:
            _dict['share_count'] = None

        # set to None if share_url (nullable) is None
        # and model_fields_set contains the field
        if self.share_url is None and "share_url" in self.model_fields_set:
            _dict['share_url'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if view_count (nullable) is None
        # and model_fields_set contains the field
        if self.view_count is None and "view_count" in self.model_fields_set:
            _dict['view_count'] = None

        # set to None if watch_time_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.watch_time_seconds is None and "watch_time_seconds" in self.model_fields_set:
            _dict['watch_time_seconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Video from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment_count": obj.get("comment_count"),
            "connected_account_id": obj.get("connected_account_id"),
            "cover_url": obj.get("cover_url"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "duration_seconds": obj.get("duration_seconds"),
            "id": obj.get("id"),
            "like_count": obj.get("like_count"),
            "linked_jobs": [VideoJobLink.from_dict(_item) for _item in obj["linked_jobs"]] if obj.get("linked_jobs") is not None else None,
            "model_id": obj.get("model_id"),
            "published_at": obj.get("published_at"),
            "remote_video_id": obj.get("remote_video_id"),
            "save_count": obj.get("save_count"),
            "share_count": obj.get("share_count"),
            "share_url": obj.get("share_url"),
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at"),
            "view_count": obj.get("view_count"),
            "watch_time_seconds": obj.get("watch_time_seconds")
        })
        return _obj


